// Phase 10: AI output schema.
// Defines the zod schema the model must conform to, and the TypeScript types
// derived from it. All 17 analysis fields are represented as arrays of
// propositions. Every proposition must carry evidence.
//
// IMPORTANT: This schema is injected into the model prompt verbatim as a
// JSON Schema description. Any change here changes the prompt — bump
// ANALYSIS_PROMPT_VERSION.

import { z } from "zod/v4";

// ── Prompt version ─────────────────────────────────────────────────────────
// Increment whenever the prompt or output schema changes materially.
export const ANALYSIS_PROMPT_VERSION = "analysis@1";

// ── Analysis output field names (17) ──────────────────────────────────────
export const AI_ANALYSIS_FIELDS = [
  "catchwords",
  "proceduralPosture",
  "materialFacts",
  "legalIssues",
  "partiesMaterialSubmissions",
  "holdingOnEachIssue",
  "reasoning",
  "possibleRatioDecidendi",
  "possibleObiterDicta",
  "orders",
  "statutesConsidered",
  "casesConsidered",
  "significance",
  "summary50Word",
  "summary150Word",
  "detailedCaseBrief",
  "teachingNote",
] as const;
export type AiAnalysisField = (typeof AI_ANALYSIS_FIELDS)[number];

// ── Confidence categories ──────────────────────────────────────────────────
export const AI_CONFIDENCE_CATEGORIES = [
  "HIGH",
  "MEDIUM",
  "LOW",
  "INSUFFICIENT_EVIDENCE",
] as const;
export type AiConfidenceCategory = (typeof AI_CONFIDENCE_CATEGORIES)[number];

// ── Uncertainty labels ─────────────────────────────────────────────────────
// The AI must apply one of these when evidence does not fully support the
// proposition. Absence of a label means the AI is confident.
export const AI_UNCERTAINTY_LABELS = [
  "NOT_STATED_IN_VERIFIED_JUDGMENT",
  "INSUFFICIENT_EVIDENCE",
  "LEGAL_CLASSIFICATION_UNCERTAIN",
  "RATIO_OBITER_REVIEW_REQUIRED",
  "HUMAN_REVIEW_REQUIRED",
] as const;
export type AiUncertaintyLabel = (typeof AI_UNCERTAINTY_LABELS)[number];

// ── Proposition review statuses ────────────────────────────────────────────
export const AI_PROPOSITION_REVIEW_STATUSES = [
  "pending",
  "approved",
  "rejected",
] as const;
export type AiPropositionReviewStatus =
  (typeof AI_PROPOSITION_REVIEW_STATUSES)[number];

// ── Run statuses ───────────────────────────────────────────────────────────
export const AI_RUN_STATUSES = [
  "DRAFT",
  "REVIEWING",
  "APPROVED",
  "REJECTED",
] as const;
export type AiRunStatus = (typeof AI_RUN_STATUSES)[number];

// ── Per-proposition zod schema ─────────────────────────────────────────────
// Each proposition in the AI output must conform to this shape.
export const AiPropositionSchema = z.object({
  /** UUID generated by the model — stable across re-runs for the same claim. */
  propositionId: z.string().min(1),
  /** The claim itself (plain text, no markdown). */
  content: z.string().min(1),
  /**
   * Paragraph identifiers (e.g. "[1]", "[12]") from the verified judgment
   * that support this proposition. Must be non-empty for HIGH/MEDIUM confidence.
   */
  supportingParagraphIds: z.array(z.string()).min(0),
  /**
   * Exact verbatim passages from the judicial text. Each passage is validated
   * byte-for-byte; passages that do not match are excluded.
   */
  supportingPassages: z.array(z.string()).min(0),
  confidenceCategory: z.enum(AI_CONFIDENCE_CATEGORIES),
  /**
   * Optional uncertainty label. Required when confidenceCategory is
   * INSUFFICIENT_EVIDENCE; recommended when the claim is uncertain.
   */
  uncertaintyLabel: z.enum(AI_UNCERTAINTY_LABELS).optional(),
});
export type AiPropositionInput = z.infer<typeof AiPropositionSchema>;

// ── Full AI output schema ──────────────────────────────────────────────────
// The model must return valid JSON matching this shape.
export const AiAnalysisOutputSchema = z.object({
  catchwords: z.array(AiPropositionSchema),
  proceduralPosture: z.array(AiPropositionSchema),
  materialFacts: z.array(AiPropositionSchema),
  legalIssues: z.array(AiPropositionSchema),
  partiesMaterialSubmissions: z.array(AiPropositionSchema),
  holdingOnEachIssue: z.array(AiPropositionSchema),
  reasoning: z.array(AiPropositionSchema),
  possibleRatioDecidendi: z.array(AiPropositionSchema),
  possibleObiterDicta: z.array(AiPropositionSchema),
  orders: z.array(AiPropositionSchema),
  statutesConsidered: z.array(AiPropositionSchema),
  casesConsidered: z.array(AiPropositionSchema),
  significance: z.array(AiPropositionSchema),
  summary50Word: z.array(AiPropositionSchema),
  summary150Word: z.array(AiPropositionSchema),
  detailedCaseBrief: z.array(AiPropositionSchema),
  teachingNote: z.array(AiPropositionSchema),
});
export type AiAnalysisOutput = z.infer<typeof AiAnalysisOutputSchema>;

// ── Validated passage record (stored in DB) ────────────────────────────────
// Produced during integrity validation; stored in research_ai_propositions.
export interface ValidatedPassage {
  text: string;
  valid: boolean;
  charStart: number | null;
  charEnd: number | null;
  /** Why validation failed (only present when valid === false). */
  failureReason?: string;
}

// ── JSON Schema description injected into the prompt ──────────────────────
// This is the string representation of the expected output format.
export const OUTPUT_JSON_SCHEMA_DESCRIPTION = `
Return a single JSON object with exactly these 17 top-level fields.
Each field is an array of proposition objects (may be empty []).

Each proposition object must have:
  propositionId    — a stable UUID string you generate
  content          — the claim as plain text
  supportingParagraphIds  — array of paragraph refs like ["[1]","[5]"]
  supportingPassages      — array of EXACT verbatim passages from the judgment
  confidenceCategory      — one of: HIGH | MEDIUM | LOW | INSUFFICIENT_EVIDENCE
  uncertaintyLabel        — optional; one of:
    NOT_STATED_IN_VERIFIED_JUDGMENT | INSUFFICIENT_EVIDENCE |
    LEGAL_CLASSIFICATION_UNCERTAIN | RATIO_OBITER_REVIEW_REQUIRED | HUMAN_REVIEW_REQUIRED

Fields: catchwords, proceduralPosture, materialFacts, legalIssues,
partiesMaterialSubmissions, holdingOnEachIssue, reasoning,
possibleRatioDecidendi, possibleObiterDicta, orders,
statutesConsidered, casesConsidered, significance,
summary50Word, summary150Word, detailedCaseBrief, teachingNote

RULES:
- Never invent facts not stated in the verified judgment text.
- Never confuse a party's submission with the court's decision.
- If a fact or holding is not stated, set confidenceCategory to INSUFFICIENT_EVIDENCE
  and uncertaintyLabel to NOT_STATED_IN_VERIFIED_JUDGMENT.
- All supportingPassages must be copied VERBATIM from the judgment text.
- Ratio/obiter classification uncertainty → use RATIO_OBITER_REVIEW_REQUIRED.
- supportingPassages must not appear in the prompt's metadata section.
`.trim();
