/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { AiGoalKpiDraft } from './aiGoalKpiDraft';

export interface AiGoalBuildResponse {
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  timeframe?: string | null;
  kpis: AiGoalKpiDraft[];
}
