/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { AiLang } from './aiLang';

export interface AiGoalBuildInput {
  /** @minLength 1 */
  prompt: string;
  lang: AiLang;
  /** @nullable */
  actingUserId?: number | null;
}
