/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type AiLang = typeof AiLang[keyof typeof AiLang];


export const AiLang = {
  en: 'en',
  ms: 'ms',
} as const;
