/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface AiRecommendation {
  action: string;
  rationale: string;
  /** @nullable */
  taskId?: number | null;
  /** @nullable */
  taskTitle?: string | null;
  /** @nullable */
  ownerName?: string | null;
}
