/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { AiLang } from './aiLang';

export interface AiTriageInput {
  /** @minLength 1 */
  title: string;
  /** @nullable */
  description?: string | null;
  lang: AiLang;
}
