/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { AiSeverity } from './aiSeverity';
import type { TaskCategory } from './taskCategory';
import type { TaskReason } from './taskReason';

export interface AiTriageResponse {
  category: TaskCategory;
  reason: TaskReason;
  /** @nullable */
  suggestedOwnerId?: number | null;
  /** @nullable */
  suggestedOwnerName?: string | null;
  rationale: string;
  confidence?: AiSeverity;
}
