/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface AttemptInput {
  /**
     * Typed attempt text. Provide this OR audioBase64.
     * @nullable
     */
  body?: string | null;
  /**
     * Base64-encoded audio of a spoken attempt (no data prefix). Transcribed server-side.
     * @nullable
     */
  audioBase64?: string | null;
  /** @nullable */
  lang?: string | null;
  /** @nullable */
  authorId?: number | null;
}
