/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { TaskDraft } from './taskDraft';

export interface CreateDraftTasksInput {
  /** @nullable */
  actingUserId?: number | null;
  drafts: TaskDraft[];
}
