/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { CreateMeetingTaskItem } from './createMeetingTaskItem';

export interface CreateMeetingTasksInput {
  /** @nullable */
  actingUserId?: number | null;
  items: CreateMeetingTaskItem[];
}
