/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { TaskCategory } from './taskCategory';
import type { TaskReason } from './taskReason';

export interface CreateMeetingTaskItem {
  actionItemIndex: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  ownerId?: number | null;
  category: TaskCategory;
  reason: TaskReason;
  /** @nullable */
  dueAt?: Date | null;
}
