/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { AiLang } from './aiLang';
import type { MeetingSegment } from './meetingSegment';

export interface CreateMeetingInput {
  /** @nullable */
  title?: string | null;
  lang: AiLang;
  segments: MeetingSegment[];
  rawTranscript: string;
  /** @nullable */
  actingUserId?: number | null;
}
