/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { OwnerCount } from './ownerCount';
import type { StatusCount } from './statusCount';
import type { TrendPoint } from './trendPoint';

export interface Dashboard {
  totalUrgent: number;
  unacknowledgedUrgent: number;
  staleBacklog: number;
  dueToday: number;
  overdue: number;
  blockedNoNote: number;
  /** @nullable */
  avgAcknowledgeMinutes: number | null;
  /** @nullable */
  avgCompleteMinutes: number | null;
  tasksByOwner: OwnerCount[];
  tasksByStatus: StatusCount[];
  completionTrend: TrendPoint[];
}
