/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Task } from './task';

export interface Digest {
  newlyStale: Task[];
  noOwner: Task[];
  approachingDue: Task[];
  inactiveOverWeek: Task[];
  recommended: Task[];
}
