/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface EvidenceInput {
  /**
     * Object path returned by the upload endpoint (e.g. /objects/uploads/uuid).
     * @minLength 1
     */
  objectPath: string;
  /** @minLength 1 */
  fileName: string;
  /** @nullable */
  contentType?: string | null;
  /** @nullable */
  fileSize?: number | null;
  /** @nullable */
  authorId?: number | null;
}
