/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type GetRecognitionRecommendationsParams = {
/**
 * The id of the manager requesting recommendations.
 */
actingUserId: number;
};
