/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type GetRecentActivityParams = {
limit?: number;
/**
 * Keyset cursor — the createdAt of the last item from the previous page. Omit for the first page.
 */
cursorCreatedAt?: Date;
/**
 * Keyset cursor — the id of the last item from the previous page. Must accompany cursorCreatedAt.
 */
cursorId?: number;
/**
 * Filter by actor — a numeric user id, or the literal "system" for automated entries.
 */
actor?: string;
/**
 * Comma-separated canonical action keys to include (e.g. "status_changed,reassigned"). Omit for all actions.
 */
actions?: string;
/**
 * When true, returns the full filtered range (unpaginated, up to a safe maximum) for spreadsheet export instead of a single page.
 */
export?: boolean;
/**
 * ISO 8601 timestamp — only include entries created at or after this instant.
 */
from?: string;
/**
 * ISO 8601 timestamp — only include entries created strictly before this instant.
 */
to?: string;
};
