/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { GoalDeliverableStats } from './goalDeliverableStats';
import type { GoalHealth } from './goalHealth';
import type { GoalStatus } from './goalStatus';
import type { Kpi } from './kpi';
import type { Task } from './task';

export interface Goal {
  id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  ownerId?: number | null;
  /** @nullable */
  ownerName?: string | null;
  /** @nullable */
  timeframe?: string | null;
  status: GoalStatus;
  health: GoalHealth;
  archived: boolean;
  kpis: Kpi[];
  deliverableStats: GoalDeliverableStats;
  deliverables: Task[];
  createdAt: Date;
  lastUpdatedAt: Date;
}
