/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface GoalDeliverableStats {
  total: number;
  done: number;
  blocked: number;
  overdue: number;
  urgent: number;
  progressPct: number;
}
