/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { GoalStatus } from './goalStatus';

export interface GoalUpdate {
  /** @minLength 1 */
  title?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  ownerId?: number | null;
  /** @nullable */
  timeframe?: string | null;
  status?: GoalStatus;
  /** @nullable */
  actingUserId?: number | null;
}
