/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type GoalHealth = typeof GoalHealth[keyof typeof GoalHealth];


export const GoalHealth = {
  on_track: 'on_track',
  at_risk: 'at_risk',
  achieved: 'achieved',
} as const;
