/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { KpiDirection } from './kpiDirection';

export interface Kpi {
  id: number;
  goalId: number;
  name: string;
  /** @nullable */
  unit?: string | null;
  targetValue: number;
  currentValue: number;
  direction: KpiDirection;
  attainmentPct: number;
  createdAt: Date;
  lastUpdatedAt: Date;
}
