/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type KpiDirection = typeof KpiDirection[keyof typeof KpiDirection];


export const KpiDirection = {
  up: 'up',
  down: 'down',
} as const;
