/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { TaskCategory } from './taskCategory';
import type { TaskReason } from './taskReason';
import type { TaskStatus } from './taskStatus';

export type ListTasksParams = {
category?: TaskCategory;
status?: TaskStatus;
reason?: TaskReason;
ownerId?: number;
/**
 * Match tasks where the user is the owner OR a collaborator.
 */
memberId?: number;
search?: string;
includeArchived?: boolean;
};
