/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { MeetingActionItem } from './meetingActionItem';
import type { MeetingAgendaItem } from './meetingAgendaItem';

export interface MeetingMinutes {
  title: string;
  summary: string;
  attendees: string[];
  agenda: MeetingAgendaItem[];
  decisions: string[];
  actionItems: MeetingActionItem[];
}
