/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { AiLang } from './aiLang';
import type { MeetingMinutes } from './meetingMinutes';
import type { MeetingSegment } from './meetingSegment';

export interface Meeting {
  id: number;
  title: string;
  lang: AiLang;
  segments: MeetingSegment[];
  rawTranscript: string;
  minutes: MeetingMinutes | null;
  /** @nullable */
  createdById: number | null;
  /** @nullable */
  createdByName: string | null;
  createdAt: Date;
}
