/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Meeting } from './meeting';
import type { Task } from './task';

export interface MeetingTasksResult {
  created: Task[];
  meeting: Meeting;
}
