/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface OwnerCount {
  /** @nullable */
  ownerId: number | null;
  ownerName: string;
  total: number;
  active: number;
  urgent: number;
  overdue: number;
}
