/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { RecentActivityEntryMeta } from './recentActivityEntryMeta';

export interface RecentActivityEntry {
  id: number;
  taskId: number;
  /** @nullable */
  taskTitle?: string | null;
  /** @nullable */
  actorId?: number | null;
  /** @nullable */
  actorName?: string | null;
  /** Canonical action key (e.g. reassigned, status_changed, edited, archived, collaborator_added). */
  action: string;
  /**
     * Before/after context for the action, rendered bilingually on the client.
     * @nullable
     */
  meta?: RecentActivityEntryMeta;
  createdAt: Date;
}
