/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface RecognitionRecommendation {
  userId: number;
  userName: string;
  role: string;
  overallScore: number;
  /** Human-readable justifications for the recommendation. */
  reasons: string[];
}
