/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { RecognitionRecommendation } from './recognitionRecommendation';

export interface RecognitionRecommendations {
  generatedAt: Date;
  bonus: RecognitionRecommendation[];
  promotion: RecognitionRecommendation[];
}
