/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface RecognitionEntry {
  userId: number;
  userName: string;
  role: string;
  /** Number of completed (done) tasks. */
  completedCount: number;
  /** Completed tasks finished on or before their deadline. */
  onTimeCount?: number;
  /** Blended speed score 0-100 (deadline margin, turnaround, vs team average). */
  speedScore: number;
  /** Volume of completed work relative to the team, 0-100. */
  throughputScore: number;
  /**
     * Average manager quality rating scaled to 0-100, or null if unrated.
     * @nullable
     */
  qualityScore?: number | null;
  /**
     * Average manager creativity rating scaled to 0-100, or null if unrated.
     * @nullable
     */
  creativityScore?: number | null;
  /** Weighted overall recognition score, 0-100. */
  overallScore: number;
  /** Number of completed tasks that have a manager assessment. */
  assessedCount: number;
  bonusEligible: boolean;
  promotionCandidate: boolean;
}
