/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { RecognitionEntry } from './recognitionEntry';

export interface RecognitionLeaderboard {
  generatedAt: Date;
  /** Team median turnaround in days; completions faster than this count as "fast". */
  fastThresholdDays: number;
  entries: RecognitionEntry[];
}
