/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { TaskCategory } from './taskCategory';
import type { TaskReason } from './taskReason';

export interface TaskDraft {
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  suggestedOwnerId?: number | null;
  /** @nullable */
  suggestedOwnerName?: string | null;
  category: TaskCategory;
  reason: TaskReason;
  /** @nullable */
  dueAt?: Date | null;
  /** @nullable */
  sourceQuote?: string | null;
}
