/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { TaskCategory } from './taskCategory';
import type { TaskReason } from './taskReason';
import type { TaskStatus } from './taskStatus';

export interface TaskUpdate {
  /** @minLength 1 */
  title?: string;
  /** @nullable */
  description?: string | null;
  category?: TaskCategory;
  reason?: TaskReason;
  status?: TaskStatus;
  /** @nullable */
  ownerId?: number | null;
  /** @nullable */
  goalId?: number | null;
  /** @nullable */
  dueAt?: Date | null;
  /** @nullable */
  positionLevel?: string | null;
  /** @nullable */
  actionVerb?: string | null;
  /** @nullable */
  qualityStandard?: string | null;
  /** @nullable */
  natureOfWork?: string | null;
  /** @nullable */
  businessUnit?: string | null;
  /** @nullable */
  deliverable?: string | null;
  /** @nullable */
  actingUserId?: number | null;
}
