/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { TaskAttemptSource } from './taskAttemptSource';

export interface TaskAttempt {
  id: number;
  taskId: number;
  /** @nullable */
  authorId?: number | null;
  /** @nullable */
  authorName?: string | null;
  body: string;
  source: TaskAttemptSource;
  createdAt: Date;
}
