/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type TaskCategory = typeof TaskCategory[keyof typeof TaskCategory];


export const TaskCategory = {
  urgent: 'urgent',
  backlog: 'backlog',
} as const;
