/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type TaskStatus = typeof TaskStatus[keyof typeof TaskStatus];


export const TaskStatus = {
  todo: 'todo',
  acknowledged: 'acknowledged',
  in_progress: 'in_progress',
  blocked: 'blocked',
  done: 'done',
} as const;
