/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type TaskAttemptSource = typeof TaskAttemptSource[keyof typeof TaskAttemptSource];


export const TaskAttemptSource = {
  text: 'text',
  voice: 'voice',
} as const;
