/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface TaskAssessment {
  id: number;
  taskId: number;
  /** @nullable */
  raterId?: number | null;
  /** @nullable */
  raterName?: string | null;
  /**
     * @minimum 1
     * @maximum 5
     */
  qualityScore: number;
  /**
     * @minimum 1
     * @maximum 5
     */
  creativityScore: number;
  /** @nullable */
  note?: string | null;
  createdAt: Date;
  updatedAt: Date;
}
