/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type TaskReason = typeof TaskReason[keyof typeof TaskReason];


export const TaskReason = {
  partner: 'partner',
  compliance: 'compliance',
  manager: 'manager',
  client: 'client',
  internal: 'internal',
  finance: 'finance',
  other: 'other',
} as const;
