/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { TaskCategory } from './taskCategory';
import type { TaskCollaborator } from './taskCollaborator';
import type { TaskReason } from './taskReason';
import type { TaskStatus } from './taskStatus';

export interface Task {
  id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  category: TaskCategory;
  reason: TaskReason;
  status: TaskStatus;
  /** @nullable */
  ownerId?: number | null;
  /** @nullable */
  ownerName?: string | null;
  /** @nullable */
  createdById?: number | null;
  /** @nullable */
  createdByName?: string | null;
  /** @nullable */
  goalId?: number | null;
  /** @nullable */
  goalTitle?: string | null;
  priorityScore: number;
  staleFlag: boolean;
  criticalFlag: boolean;
  archived: boolean;
  /** @nullable */
  latestNote?: string | null;
  noteCount: number;
  createdAt: Date;
  /** @nullable */
  dueAt?: Date | null;
  /** @nullable */
  acknowledgedAt?: Date | null;
  lastUpdatedAt: Date;
  /** @nullable */
  lastNudgedAt?: Date | null;
  /** @nullable */
  positionLevel?: string | null;
  /** @nullable */
  actionVerb?: string | null;
  /** @nullable */
  qualityStandard?: string | null;
  /** @nullable */
  natureOfWork?: string | null;
  /** @nullable */
  businessUnit?: string | null;
  /** @nullable */
  deliverable?: string | null;
  collaborators?: TaskCollaborator[];
}
