/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface TaskEvidence {
  id: number;
  taskId: number;
  /** @nullable */
  authorId?: number | null;
  /** @nullable */
  authorName?: string | null;
  objectPath: string;
  fileName: string;
  /** @nullable */
  contentType?: string | null;
  /** @nullable */
  fileSize?: number | null;
  createdAt: Date;
}
