/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

/**
 * Before/after context for the action, rendered bilingually on the client.
 * @nullable
 */
export type TaskActivityMeta = { [key: string]: unknown } | null;
