/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { UserRole } from './userRole';

export interface UpdateUserInput {
  role: UserRole;
  /** @nullable */
  actingUserId?: number | null;
}
