/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface UpsertAssessmentInput {
  /** The id of the manager submitting the assessment. */
  actingUserId: number;
  /**
     * How well the task was completed (1 = poor, 5 = excellent).
     * @minimum 1
     * @maximum 5
     */
  qualityScore: number;
  /**
     * How creative the approach was (1 = routine, 5 = highly creative).
     * @minimum 1
     * @maximum 5
     */
  creativityScore: number;
  /**
     * Optional justification referencing the staff's attempts and evidence.
     * @nullable
     */
  note?: string | null;
}
