/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { UserRole } from './userRole';

export interface User {
  id: number;
  name: string;
  role: UserRole;
  title?: string | null;
  email: string;
  activeStatus: boolean;
  /** @nullable */
  phone?: string | null;
  whatsappOptIn: boolean;
  /** @nullable */
  whatsappOptInAt?: Date | null;
  smsOptIn: boolean;
  /** @nullable */
  smsOptInAt?: Date | null;
}
