/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { UserRole } from './userRole';

export interface UserInput {
  /** @minLength 1 */
  name: string;
  role: UserRole;
  title?: string | null;
  /** @minLength 1 */
  email: string;
  activeStatus?: boolean;
}
