/**
 * Reviewed non-producers reachable through eager router imports. This is not a
 * blanket exemption for app/router tests: a NEW suite must be audited or isolated.
 * If adding a queue-producing request to one of these suites, remove its entry
 * and opt it into isolatedQueueSuites before running it.
 */
export const queueAuditExceptions: Readonly<Record<string, string>> = {
  "research/domain/stateMachines.test.ts": "Every queue call supplies the disposable schema client explicitly.",
  "research/phase09.test.ts": "Quotation and citation-integrity operations do not enqueue.",
  "research/phase10.test.ts": "Synchronous runAiAnalysis, not enqueueAiAnalysis.",
  "research/phase11a.test.ts": "Authority extraction fixtures; no enqueue invocation.",
  "research/phase11b.test.ts": "Workspace folder/collection operations only.",
  "research/phase12a.test.ts": "Audit/export/rights and seeded analysis-run checks.",
  "research/phase12b.test.ts": "Export format/scope/visibility operations only.",
  "research/phase12c.test.ts": "Seeded analysis/export/security data operations only.",
  "routes/research-admin-headnotes-approval.test.ts": "Headnote publication approval does not enqueue.",
  "routes/research-publication-auth.test.ts": "Editorial publication authorization, not ingest approval.",
  "routes/admin-master-access.routes.test.ts": "Admin access checks, no approval/bulk producer requests.",
  ...Object.fromEntries([
    "sya/routes/matters/billing-rate-cards.test.ts",
    "sya/routes/matters/matters.test.ts",
    "routes/admin-auth.test.ts",
    "routes/admin-contributions.test.ts",
    "routes/admin-payment-refresh.test.ts",
    "routes/admin-unbind-microsoft.test.ts",
    "routes/contributions.test.ts",
    "routes/convey-billing-rate-cards.test.ts",
    "routes/landing-admin-auth.test.ts",
    "routes/master-practitioner-regression.test.ts",
    "routes/payment-access-regression.test.ts",
    "routes/shared-uploads.test.ts",
    "routes/storage-access.test.ts",
    "routes/stripe-checkout.test.ts",
    "routes/stripe-customer-portal.test.ts",
    "routes/stripe-webhook-retry.test.ts",
    "lit/routes/billing-named-lawyer.test.ts",
    "lit/routes/billing-rate-cards-irac.test.ts",
    "lit/routes/billing-rate-cards.test.ts",
    "lit/routes/irac-analyze-matter-context.test.ts",
    "lit/routes/lawyes.test.ts",
    "lit/routes/lit-bundles.test.ts",
    "lit/routes/lit-uploads.test.ts",
    "lit/routes/matter-preparation.test.ts",
    "lib/aiRateLimit-noauth.test.ts",
    "lib/caseBilling.test.ts",
    "lib/caseClients.test.ts",
    "lib/caseIntakeBriefingIsolation.test.ts",
    "lib/matter-files.test.ts",
    "lib/personas.test.ts",
    "crim/routes/billing-rate-cards.test.ts",
    "crim/routes/crim-matters.test.ts",
    "corp/routes/billing-rate-cards.test.ts",
    "corp/routes/corp-security.test.ts",
    "corp/routes/workflow.test.ts",
    "corp/routes/legal/ai-tools-matter-context.test.ts",
    "ccb/routes/billing-rate-cards.test.ts",
    "ccb/routes/gemini-persistence-isolation.audit.test.ts",
    "ccb/routes/matters.test.ts",
    "accident/billing-rate-cards.test.ts",
    "accident/matters.test.ts",
  ].map(file => [file, "Eager app import only; requests exercise unrelated portal routes, not research producers."])),
};