import { useMemo, useState } from "react";
import { GATEWAYS, NOT_STATED, REPORTS, type Report, filterReports, exportRecords, reportText, validatePublication } from "@/fixtures/lawyes-preview";

const fields = [["party","Party / title"],["case","Case / citation"],["catchwords","Catchwords"],["fullText","Full report text"],["court","Court"],["coram","Judge / coram"],["counsel","Counsel"],["practiceArea","Practice area"],["legislation","Legislation"],["issue","Issue"],["outcome","Outcome"],["treatment","Judicial treatment"],["sourcePublisher","Source publisher"],["status","Status"]] as const;
const blank = {
  ...Object.fromEntries(fields.map(([x]) => [x, ""])),
  from: "",
  to: "",
} as Record<string, string>;
const pin = (points: readonly string[]) => <>{points.map(p => <a className="pin" href={`#p-${p.replace(/[^\w]/g,"")}`} key={p}>¶ {p}</a>)}</>;
function download(name: string, text: string, type: string) { const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([text],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href); }
function docxDownload(text: string) {
  const enc=new TextEncoder(), esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;"), files=[
    ["[Content_Types].xml",'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'],
    ["_rels/.rels",'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'],
    ["word/document.xml",`<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${text.split("\n").map(s=>`<w:p><w:r><w:t>${esc(s)}</w:t></w:r></w:p>`).join("")}<w:sectPr/></w:body></w:document>`],
  ].map(([name,body])=>({name,bytes:enc.encode(body)})); const u16=(n:number)=>[n&255,n>>>8&255],u32=(n:number)=>[n&255,n>>>8&255,n>>>16&255,n>>>24&255];
  let offset=0; const chunks:Uint8Array[]=[],central:Uint8Array[]=[]; const crc=(b:Uint8Array)=>{let c=-1;for(const v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^(0xedb88320&-(c&1));}return(c^-1)>>>0;};
  for(const f of files){const n=enc.encode(f.name),c=crc(f.bytes),local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(c),...u32(f.bytes.length),...u32(f.bytes.length),...u16(n.length),...u16(0),...n,...f.bytes]);chunks.push(local);central.push(new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(c),...u32(f.bytes.length),...u32(f.bytes.length),...u16(n.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...n]));offset+=local.length;}
  const size=central.reduce((n,x)=>n+x.length,0);chunks.push(...central,new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(files.length),...u16(files.length),...u32(size),...u32(offset),...u16(0)])); const out=new Uint8Array(chunks.reduce((n,x)=>n+x.length,0));let p=0;chunks.forEach(x=>{out.set(x,p);p+=x.length;}); const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([out],{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"}));a.download="lawyes-report.docx";a.click();URL.revokeObjectURL(a.href);
}
function Reader({ r }: {r: Report}) {
  if (!r.report) return <aside className="reader"><h2>{r.title}</h2><b>Access record</b><p>This record is pending editorial review. It does not imply a substantive LAWYes report or analysis.</p><Meta r={r}/></aside>;
  const x=r.report;
  const pointIds = [...x.facts,...x.proceduralHistory,...x.ratio,...x.obiter,x.disposition,...x.issues,...x.authorities].flatMap(v=>v.pinpoints).filter((p,i,a)=>a.indexOf(p)===i);
  const section=(title:string, items: readonly {text:string;pinpoints:readonly string[]}[]) => <section><h3>{title}</h3>{items.map((v,i)=><p key={i}>{v.text} {pin(v.pinpoints)}</p>)}</section>;
  return <aside className="reader"><p className="eyebrow">LAWYES REPORT READER · PUBLISHED PREVIEW</p><h2>{r.title}</h2><Meta r={r}/><nav aria-label="Report table of contents">{[["headnote","Headnote"],["facts","Facts"],["procedural-history","Procedural history"],["issues-holdings","Issues / holdings"],["ratio","Ratio"],["obiter","Obiter"],["orders","Orders"],["legislation-authorities","Legislation / authorities"],["paragraphs","Paragraphs"],["related-reports","Related"],["revision-history","Revision history"]].map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</nav>
    <section id="headnote"><h3>Original headnote</h3><p>{x.headnote}</p></section><section id="facts">{section("Material facts",x.facts)}</section><section id="procedural-history">{section("Procedural history",x.proceduralHistory)}</section>
    <section id="issues-holdings"><h3>Issues and holdings</h3>{x.issues.map(v=><p key={v.issue}><b>{v.issue}</b><br/>{v.holding} {pin(v.pinpoints)}</p>)}</section>
    <section id="ratio">{section("Ratio decidendi",x.ratio)}</section><section id="obiter">{section("Separate obiter",x.obiter)}</section><section id="orders"><h3>Disposition, orders and costs</h3><p>{x.disposition.text} {pin(x.disposition.pinpoints)}</p></section>
    <section id="legislation-authorities"><h3>Legislation</h3><p>{x.legislation.join(" · ")}</p><h3>Authorities and treatment</h3>{x.authorities.map(a=><p key={a.name}>{a.name} — {a.treatment} {pin(a.pinpoints)}</p>)}</section>
    <section id="paragraphs"><h3>Paragraph pane</h3><div aria-label="Verified pinpoint anchors">{pointIds.map(p=><span id={`p-${p.replace(/[^\w]/g,"")}`} key={p}/>)}</div>{x.paragraphs.map(p=><p id={`judgment-p-${p.number.replace(/[^\w]/g,"")}`} key={p.number}><b>¶ {p.number}</b> {p.text}</p>)}</section>
    <section id="related-reports"><h3>Related reports</h3><p>{REPORTS.filter(v=>v.id!==r.id&&v.practiceAreas.some(a=>r.practiceAreas.includes(a))).slice(0,3).map(v=>v.title).join(" · ")||NOT_STATED}</p></section><section id="revision-history"><h3>Revision history</h3><p>{r.revisionHistory.join(" ")}</p></section>
  </aside>;
}
function Meta({r}:{r:Report}) { const [copied,setCopied]=useState(false); return <section className="meta"><p><b>Citation/case number:</b> {r.citation||NOT_STATED} <button onClick={()=>{navigator.clipboard?.writeText(r.citation||NOT_STATED);setCopied(true)}}>Copy citation</button> <span aria-live="polite">{copied?"Citation copied.":""}</span></p><p><b>Court/registry/date:</b> {r.court} · {r.registry} · {r.date}</p><p><b>Coram/counsel:</b> {r.coram} · {r.counsel}</p><p><b>Practice tags:</b> {r.practiceAreas.join(", ")}</p><p><b>Source:</b> <a href={r.sourceUrl} target="_blank" rel="noopener noreferrer">{r.sourcePublisher} ↗</a></p><p><b>Full-text access:</b> {r.status==="Published"?"Preview report available; original judgment at official source.":"Official collection gateway; direct document not stated."}</p><p><b>Status/reviewer/date:</b> {r.status} · {r.reviewer} · {r.verificationDate}</p></section> }
export default function LawYesSafePreview() {
 const [filters,setFilters]=useState(blank),[selected,setSelected]=useState<Report>(REPORTS[0]),[sort,setSort]=useState("title"),[matter,setMatter]=useState("SFI access research"),[instruction,setInstruction]=useState("Prepare local research note."),[doc,setDoc]=useState("Affidavit"),[checks,setChecks]=useState([false,false,false]);
 const results=useMemo(()=>filterReports(REPORTS,filters).sort((a,b)=>sort==="date"?a.isoDate.localeCompare(b.isoDate):sort==="court"?a.court.localeCompare(b.court):a.title.localeCompare(b.title)),[filters,sort]);
 const structured=JSON.stringify(exportRecords(results),null,2); const access=selected.status==="Access record";
 return <main className="safe-preview"><style>{`.safe-preview{max-width:1500px;margin:auto;padding:24px;font:15px system-ui;color:#182230}.safe-preview a{color:#075c9b}.safe-head,.safe-layout,.demo-grid{display:grid;gap:18px}.safe-head{grid-template-columns:1fr auto}.safe-brand{font-size:28px;font-weight:800;text-decoration:none}.safe-brand span,.eyebrow{color:#b14120}.safe-layout{grid-template-columns:260px minmax(280px,1fr) minmax(360px,1.4fr);align-items:start}.filters,.results,.reader,.demo-grid article{border:1px solid #cbd5df;border-radius:8px;padding:16px}.filters label{display:block;margin:9px 0}.filters input,select,textarea{box-sizing:border-box;width:100%;padding:7px}.case{display:block;width:100%;text-align:left;margin:8px 0;padding:10px;background:white;border:1px solid #d7dee5;border-radius:6px}.selected{border-left:5px solid #b14120}.reader{max-height:78vh;overflow:auto}.reader nav{display:flex;flex-wrap:wrap;gap:9px}.reader section{border-top:1px solid #e3e8ed;margin-top:14px}.pin{font-size:12px;margin-left:5px;white-space:nowrap}.demo-grid{grid-template-columns:repeat(3,1fr);margin-top:20px}.exports{display:flex;flex-wrap:wrap;gap:7px}.status{font-weight:700}@media(max-width:900px){.safe-layout{grid-template-columns:1fr}.reader{max-height:none}.demo-grid{grid-template-columns:1fr}.safe-head{grid-template-columns:1fr}}@media print{@page{size:A4;margin:15mm}.filters,.results,.demo-grid,.safe-head strong,button,footer{display:none!important}.safe-preview{max-width:none;padding:0;font-size:10pt}.safe-layout{display:block}.reader{border:0;max-height:none;overflow:visible}.reader section{break-inside:avoid}.pin{color:#000;text-decoration:none}}`}</style>
 <header className="safe-head"><a className="safe-brand" href="/">LAW<span>Yes</span></a><strong>SAFE PREVIEW</strong><p>Local-only static fixture. No account, network request, storage, upload, payment, or server write.</p></header>
 <section><p className="eyebrow">MALAYSIAN LEGAL RESEARCH</p><h1>Verified report preview</h1><p>Two lawyer-reviewed preview reports are published only because their official source, paragraph support, and human approval are recorded in this fixture.</p></section>
  <section className="safe-layout"><aside className="filters"><h2>Search library</h2>{fields.map(([key,label])=><label key={key}>{label}<input aria-label={label} value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}/></label>)}<label>From <input type="date" value={filters.from ?? ""} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>To <input type="date" value={filters.to ?? ""} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><button onClick={()=>setFilters(blank)}>Clear filters</button></aside>
 <section className="results"><h2>{results.length} records</h2><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option value="title">Title</option><option value="court">Court</option><option value="date">Date</option></select></label><div className="exports"><button onClick={()=>download("lawyes-results.csv",["Title,Citation,Court,Status",...results.map(r=>`"${r.title.replace(/"/g,'""')}","${r.citation}","${r.court}","${r.status}"`)].join("\n"),"text/csv")}>CSV filtered results</button><button onClick={()=>download("lawyes-report.json",structured,"application/json")}>Structured JSON</button>{!access&&<><button onClick={()=>download("lawyes-report.txt",reportText(selected),"text/plain")}>Text</button><button onClick={()=>docxDownload(reportText(selected))}>DOCX</button><button onClick={()=>window.print()}>Print / PDF</button></>}</div>{results.length===0?<p role="status">No reports match these filters. Clear filters to restore the fixture.</p>:results.map(r=><button className={`case ${selected.id===r.id?"selected":""}`} onClick={()=>setSelected(r)} key={r.id}><span className="status">{r.status}</span><br/><b>{r.title}</b><br/>{r.citation||NOT_STATED} · {r.court}</button>)}</section><Reader r={selected}/></section>
 <section className="demo-grid"><article><h2>Matter Workspace</h2><label>Sample matter<select value={matter} onChange={e=>setMatter(e.target.value)}><option>SFI access research</option><option>Tuaran criminal trial</option></select></label><label>Client / instructions<textarea value={instruction} onChange={e=>setInstruction(e.target.value)}/></label><p>Local session: {matter}</p></article><article><h2>Practical Document Studio</h2><label>Cause-paper type<select value={doc} onChange={e=>setDoc(e.target.value)}><option>Affidavit</option><option>Written submission</option><option>Notice of application</option></select></label><button onClick={()=>setInstruction(`LOCAL PREVIEW DRAFT — ${doc}\nMatter: ${matter}\nInstructions: ${instruction}`)}>Generate deterministic local preview draft</button><pre>{instruction}</pre></article><article><h2>Filing Readiness</h2>{["Authority access checked","Citation verified","Human review completed"].map((x,i)=><label key={x}><input type="checkbox" checked={checks[i]} onChange={()=>setChecks(checks.map((v,n)=>n===i?!v:v))}/>{x}</label>)}<p><b>{checks.every(Boolean)?"Ready for local checklist review":"Checks outstanding"}</b></p></article></section>
 <section><h2>Official-source gateways</h2>{GATEWAYS.map(([n,u])=><p key={n}><a href={u} target="_blank" rel="noopener noreferrer">{n} ↗</a></p>)}</section><footer>Preview fixture only · Publication gate validation: {REPORTS.every(validatePublication)?"passed":"failed"}.</footer></main>;
}