/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MySyariahAi API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Verify access code
 */
export const VerifyAccessCodeBody = zod.object({
  accessCode: zod.string(),
});

export const VerifyAccessCodeResponse = zod.object({
  authenticated: zod.boolean(),
  user: zod
    .object({
      id: zod.number(),
      name: zod.string(),
      role: zod.string(),
      accessCode: zod.string(),
    })
    .optional(),
});

/**
 * @summary Get current session
 */
export const GetSessionResponse = zod.object({
  authenticated: zod.boolean(),
  user: zod
    .object({
      id: zod.number(),
      name: zod.string(),
      role: zod.string(),
      accessCode: zod.string(),
    })
    .optional(),
});

/**
 * @summary List all legal provision topics
 */
export const ListProvisionsQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  search: zod.coerce.string().optional(),
});

export const ListProvisionsResponseItem = zod.object({
  id: zod.number(),
  category: zod.string(),
  categoryBm: zod.string(),
  titleEn: zod.string(),
  titleBm: zod.string(),
  overviewEn: zod.string(),
  overviewBm: zod.string(),
  principlesEn: zod.string(),
  principlesBm: zod.string(),
  legislationEn: zod.string(),
  legislationBm: zod.string(),
  practicalNotesEn: zod.string(),
  practicalNotesBm: zod.string(),
  relatedCases: zod.string().optional(),
  order: zod.number(),
});
export const ListProvisionsResponse = zod.array(ListProvisionsResponseItem);

/**
 * @summary Get a specific provision topic
 */
export const GetProvisionParams = zod.object({
  id: zod.coerce.number(),
});

export const GetProvisionResponse = zod.object({
  id: zod.number(),
  category: zod.string(),
  categoryBm: zod.string(),
  titleEn: zod.string(),
  titleBm: zod.string(),
  overviewEn: zod.string(),
  overviewBm: zod.string(),
  principlesEn: zod.string(),
  principlesBm: zod.string(),
  legislationEn: zod.string(),
  legislationBm: zod.string(),
  practicalNotesEn: zod.string(),
  practicalNotesBm: zod.string(),
  relatedCases: zod.string().optional(),
  order: zod.number(),
});

/**
 * @summary List provision categories with counts
 */
export const ListProvisionCategoriesResponseItem = zod.object({
  category: zod.string(),
  categoryBm: zod.string().optional(),
  count: zod.number(),
});
export const ListProvisionCategoriesResponse = zod.array(
  ListProvisionCategoriesResponseItem,
);

/**
 * @summary List case laws
 */
export const ListCasesQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  search: zod.coerce.string().optional(),
  year: zod.coerce.string().optional(),
});

export const ListCasesResponseItem = zod.object({
  id: zod.number(),
  caseName: zod.string(),
  caseNameBm: zod.string().optional(),
  citation: zod.string(),
  year: zod.string(),
  court: zod.string(),
  courtBm: zod.string().optional(),
  judge: zod.string().optional(),
  factsEn: zod.string(),
  factsBm: zod.string(),
  issuesEn: zod.string(),
  issuesBm: zod.string(),
  heldEn: zod.string(),
  heldBm: zod.string(),
  significanceEn: zod.string(),
  significanceBm: zod.string(),
  category: zod.string(),
  categoryBm: zod.string(),
  tags: zod.string().optional(),
  legislation: zod.string().optional(),
});
export const ListCasesResponse = zod.array(ListCasesResponseItem);

/**
 * @summary Get a specific case
 */
export const GetCaseParams = zod.object({
  id: zod.coerce.number(),
});

export const GetCaseResponse = zod.object({
  id: zod.number(),
  caseName: zod.string(),
  caseNameBm: zod.string().optional(),
  citation: zod.string(),
  year: zod.string(),
  court: zod.string(),
  courtBm: zod.string().optional(),
  judge: zod.string().optional(),
  factsEn: zod.string(),
  factsBm: zod.string(),
  issuesEn: zod.string(),
  issuesBm: zod.string(),
  heldEn: zod.string(),
  heldBm: zod.string(),
  significanceEn: zod.string(),
  significanceBm: zod.string(),
  category: zod.string(),
  categoryBm: zod.string(),
  tags: zod.string().optional(),
  legislation: zod.string().optional(),
});

/**
 * @summary List case categories with counts
 */
export const ListCaseCategoriesResponseItem = zod.object({
  category: zod.string(),
  categoryBm: zod.string().optional(),
  count: zod.number(),
});
export const ListCaseCategoriesResponse = zod.array(
  ListCaseCategoriesResponseItem,
);

/**
 * @summary List cause paper templates
 */
export const ListCausePapersQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  search: zod.coerce.string().optional(),
});

export const ListCausePapersResponseItem = zod.object({
  id: zod.number(),
  titleEn: zod.string(),
  titleBm: zod.string(),
  category: zod.string(),
  categoryBm: zod.string(),
  descriptionEn: zod.string(),
  descriptionBm: zod.string(),
  templateEn: zod.string(),
  templateBm: zod.string(),
  formNumber: zod.string().optional(),
  requiredFields: zod.string().optional(),
  order: zod.number(),
});
export const ListCausePapersResponse = zod.array(ListCausePapersResponseItem);

/**
 * @summary Get a specific cause paper template
 */
export const GetCausePaperParams = zod.object({
  id: zod.coerce.number(),
});

export const GetCausePaperResponse = zod.object({
  id: zod.number(),
  titleEn: zod.string(),
  titleBm: zod.string(),
  category: zod.string(),
  categoryBm: zod.string(),
  descriptionEn: zod.string(),
  descriptionBm: zod.string(),
  templateEn: zod.string(),
  templateBm: zod.string(),
  formNumber: zod.string().optional(),
  requiredFields: zod.string().optional(),
  order: zod.number(),
});

/**
 * @summary List procedural workflows
 */
export const ListWorkflowsQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  search: zod.coerce.string().optional(),
});

export const ListWorkflowsResponseItem = zod.object({
  id: zod.number(),
  titleEn: zod.string(),
  titleBm: zod.string(),
  category: zod.string(),
  categoryBm: zod.string(),
  descriptionEn: zod.string(),
  descriptionBm: zod.string(),
  stepsJson: zod.string(),
  estimatedTimeline: zod.string().optional(),
  requiredDocuments: zod.string().optional(),
  courtFees: zod.string().optional(),
  order: zod.number(),
});
export const ListWorkflowsResponse = zod.array(ListWorkflowsResponseItem);

/**
 * @summary Get a specific workflow
 */
export const GetWorkflowParams = zod.object({
  id: zod.coerce.number(),
});

export const GetWorkflowResponse = zod.object({
  id: zod.number(),
  titleEn: zod.string(),
  titleBm: zod.string(),
  category: zod.string(),
  categoryBm: zod.string(),
  descriptionEn: zod.string(),
  descriptionBm: zod.string(),
  stepsJson: zod.string(),
  estimatedTimeline: zod.string().optional(),
  requiredDocuments: zod.string().optional(),
  courtFees: zod.string().optional(),
  order: zod.number(),
});

/**
 * @summary List glossary terms
 */
export const ListGlossaryTermsQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  search: zod.coerce.string().optional(),
  letter: zod.coerce.string().optional(),
});

export const ListGlossaryTermsResponseItem = zod.object({
  id: zod.number(),
  termArabic: zod.string().optional(),
  termBm: zod.string(),
  termEn: zod.string(),
  definitionEn: zod.string(),
  definitionBm: zod.string(),
  category: zod.string(),
  categoryBm: zod.string(),
  source: zod.string().optional(),
  practicalExample: zod.string().optional(),
});
export const ListGlossaryTermsResponse = zod.array(
  ListGlossaryTermsResponseItem,
);

/**
 * @summary Get a specific glossary term
 */
export const GetGlossaryTermParams = zod.object({
  id: zod.coerce.number(),
});

export const GetGlossaryTermResponse = zod.object({
  id: zod.number(),
  termArabic: zod.string().optional(),
  termBm: zod.string(),
  termEn: zod.string(),
  definitionEn: zod.string(),
  definitionBm: zod.string(),
  category: zod.string(),
  categoryBm: zod.string(),
  source: zod.string().optional(),
  practicalExample: zod.string().optional(),
});

/**
 * @summary List legislation references
 */
export const ListLegislationQueryParams = zod.object({
  search: zod.coerce.string().optional(),
});

export const ListLegislationResponseItem = zod.object({
  id: zod.number(),
  titleEn: zod.string(),
  titleBm: zod.string(),
  actNumber: zod.string().optional(),
  year: zod.string().optional(),
  descriptionEn: zod.string(),
  descriptionBm: zod.string(),
  keyProvisionsEn: zod.string().optional(),
  keyProvisionsBm: zod.string().optional(),
  category: zod.string().optional(),
  order: zod.number(),
});
export const ListLegislationResponse = zod.array(ListLegislationResponseItem);

/**
 * @summary Get a specific legislation
 */
export const GetLegislationParams = zod.object({
  id: zod.coerce.number(),
});

export const GetLegislationResponse = zod.object({
  id: zod.number(),
  titleEn: zod.string(),
  titleBm: zod.string(),
  actNumber: zod.string().optional(),
  year: zod.string().optional(),
  descriptionEn: zod.string(),
  descriptionBm: zod.string(),
  keyProvisionsEn: zod.string().optional(),
  keyProvisionsBm: zod.string().optional(),
  category: zod.string().optional(),
  order: zod.number(),
});

/**
 * @summary Get dashboard statistics
 */
export const GetDashboardStatsResponse = zod.object({
  totalProvisions: zod.number(),
  totalCases: zod.number(),
  totalCausePapers: zod.number(),
  totalWorkflows: zod.number(),
  totalGlossaryTerms: zod.number(),
  totalLegislation: zod.number(),
});

/**
 * @summary Get case distribution by category
 */
export const GetCaseDistributionResponseItem = zod.object({
  category: zod.string(),
  categoryBm: zod.string().optional(),
  count: zod.number(),
});
export const GetCaseDistributionResponse = zod.array(
  GetCaseDistributionResponseItem,
);

/**
 * @summary List AI conversations
 */
export const ListGeminiConversationsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});
export const ListGeminiConversationsResponse = zod.array(
  ListGeminiConversationsResponseItem,
);

/**
 * @summary Create a new AI conversation
 */
export const CreateGeminiConversationBody = zod.object({
  title: zod.string(),
});

/**
 * @summary Get a conversation with messages
 */
export const GetGeminiConversationParams = zod.object({
  conversationId: zod.coerce.number(),
});

export const GetGeminiConversationResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
  messages: zod.array(
    zod.object({
      id: zod.number(),
      conversationId: zod.number(),
      role: zod.enum(["user", "assistant"]),
      content: zod.string(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Delete a conversation
 */
export const DeleteGeminiConversationParams = zod.object({
  conversationId: zod.coerce.number(),
});

/**
 * @summary Send a message to AI (streaming SSE response)
 */
export const SendGeminiMessageParams = zod.object({
  conversationId: zod.coerce.number(),
});

export const SendGeminiMessageBody = zod.object({
  content: zod.string(),
});
