import { Router } from "express";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";
import { logger } from "../../lib/logger";
import { exportPlainText, normalizeExportLines, type ExportInline } from "../../utils/exportFormatting";

const router = Router();

function buildParagraphs(content: string): Paragraph[] {
  const paragraphs: Paragraph[] = [];

  for (const line of normalizeExportLines(content)) {
    if (line.kind === "blank") {
      paragraphs.push(new Paragraph({ children: [new TextRun("")] }));
      continue;
    }

    if (line.kind === "heading") {
      const level = line.level === 1
        ? HeadingLevel.HEADING_1
        : line.level === 2
          ? HeadingLevel.HEADING_2
          : HeadingLevel.HEADING_3;
      const size = line.level === 1 ? 32 : line.level === 2 ? 28 : 24;
      paragraphs.push(
        new Paragraph({
          heading: level,
          children: line.runs.map((run) => new TextRun({
            text: run.text, bold: true, italics: run.italics, size,
          })),
        }),
      );
      continue;
    }

    if (line.kind === "bullet") {
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          children: toTextRuns(line.runs),
        }),
      );
      continue;
    }

    if (line.kind === "numbered" && /^\d+\.$/.test(line.marker ?? "")) {
      paragraphs.push(
        new Paragraph({
          numbering: { reference: "default-numbering", level: 0 },
          children: toTextRuns(line.runs),
        }),
      );
      continue;
    }

    paragraphs.push(
      new Paragraph({
        children: line.kind === "numbered"
          ? [new TextRun(`${line.marker}\t`), ...toTextRuns(line.runs)]
          : toTextRuns(line.runs),
      }),
    );
  }

  return paragraphs;
}

function toTextRuns(runs: ExportInline[]): TextRun[] {
  return runs.map((run) => new TextRun({
    text: run.text,
    bold: run.bold,
    italics: run.italics,
    font: run.code ? "Courier New" : undefined,
  }));
}

function safeFilename(name: string): string {
  return (
    name
      .replace(/[^a-zA-Z0-9-_ ]/g, "")
      .trim()
      .replace(/\s+/g, "_")
      .slice(0, 80) || "Document"
  );
}

router.post("/docx", async (req, res) => {
  try {
    const { title, content } = (req.body ?? {}) as {
      title?: string;
      content?: string;
    };

    if (!content || typeof content !== "string" || content.trim().length === 0) {
      return res.status(400).json({ error: "content is required" });
    }

    const docTitle = exportPlainText((title && title.trim()) || "MyLitAi Document");

    const headerParagraph = new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: docTitle, bold: true, size: 36 })],
    });

    const metaParagraph = new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: `Generated by MyLitAi  •  ${new Date().toLocaleDateString(
            "en-GB",
            { day: "2-digit", month: "long", year: "numeric" },
          )}`,
          italics: true,
          size: 18,
          color: "666666",
        }),
      ],
    });

    const spacer = new Paragraph({ children: [new TextRun("")] });

    const doc = new Document({
      creator: "MyLitAi",
      title: docTitle,
      description: "AI-generated legal document",
      numbering: {
        config: [
          {
            reference: "default-numbering",
            levels: [
              {
                level: 0,
                format: "decimal",
                text: "%1.",
                alignment: AlignmentType.LEFT,
              },
            ],
          },
        ],
      },
      styles: {
        default: {
          document: {
            run: { font: "Calibri", size: 22 },
          },
        },
      },
      sections: [
        {
          properties: {
            page: {
              size: { width: 11906, height: 16838 },
            },
          },
          children: [
            headerParagraph,
            metaParagraph,
            spacer,
            ...buildParagraphs(content),
          ],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    const filename = `${safeFilename(docTitle)}_${new Date()
      .toISOString()
      .slice(0, 10)}.docx`;

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    );
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${filename}"`,
    );
    res.setHeader("Content-Length", buffer.length.toString());
    return res.end(buffer);
  } catch (err) {
    logger.error({ err }, "DOCX export failed");
    return res.status(500).json({ error: "Failed to generate DOCX" });
  }
});

export default router;
