import { Router } from "express";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";
import { logger } from "../../lib/logger";

const router = Router();

// A line that is nothing but repeated rule characters (dashes, asterisks,
// underscores, equals, box-drawing) — optionally spaced out like "- - - - -".
// The AI sometimes emits these as visual dividers; Word renders them as noise,
// so we drop them and rely on blank lines for separation instead.
function isHorizontalRule(line: string): boolean {
  const stripped = line.replace(/\s+/g, "");
  return stripped.length >= 3 && /^[-*_=─—–]+$/.test(stripped);
}

// Remove stray Markdown emphasis markers that survive as literal characters
// (e.g. a lone "**" or "*" the model failed to close). parseInline handles
// well-formed pairs; this cleans up the leftovers so no raw asterisks appear.
function stripStrayEmphasis(text: string): string {
  return text
    // collapse any run of 2+ asterisks/underscores into nothing
    .replace(/\*{2,}/g, "")
    .replace(/_{2,}/g, "");
}

function buildParagraphs(content: string): Paragraph[] {
  const lines = content.replace(/\r\n/g, "\n").split("\n");
  const paragraphs: Paragraph[] = [];

  for (const rawLine of lines) {
    const line = rawLine.replace(/\s+$/, "");

    // Drop horizontal-rule / divider lines entirely — emit a blank line so the
    // surrounding sections stay visually separated without the dash strand.
    if (isHorizontalRule(line.trim())) {
      paragraphs.push(new Paragraph({ children: [new TextRun("")] }));
      continue;
    }

    if (line.trim() === "") {
      paragraphs.push(new Paragraph({ children: [new TextRun("")] }));
      continue;
    }

    const h1 = line.match(/^#\s+(.+)$/);
    const h2 = line.match(/^##\s+(.+)$/);
    const h3 = line.match(/^###\s+(.+)$/);

    if (h1) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun({ text: h1[1], bold: true, size: 32 })],
        }),
      );
      continue;
    }
    if (h2) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: h2[1], bold: true, size: 28 })],
        }),
      );
      continue;
    }
    if (h3) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun({ text: h3[1], bold: true, size: 24 })],
        }),
      );
      continue;
    }

    if (/^[-*•]\s+/.test(line)) {
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          children: parseInline(line.replace(/^[-*•]\s+/, "")),
        }),
      );
      continue;
    }

    const numbered = line.match(/^(\d+)\.\s+(.+)$/);
    if (numbered) {
      paragraphs.push(
        new Paragraph({
          numbering: { reference: "default-numbering", level: 0 },
          children: parseInline(numbered[2]),
        }),
      );
      continue;
    }

    paragraphs.push(
      new Paragraph({
        children: parseInline(line),
      }),
    );
  }

  return paragraphs;
}

function parseInline(text: string): TextRun[] {
  const tokens = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)/g);
  const runs: TextRun[] = [];
  for (const tok of tokens) {
    if (!tok) continue;
    if (/^\*\*[^*]+\*\*$/.test(tok)) {
      runs.push(new TextRun({ text: tok.slice(2, -2), bold: true }));
    } else if (/^\*[^*]+\*$/.test(tok)) {
      runs.push(new TextRun({ text: tok.slice(1, -1), italics: true }));
    } else if (/^`[^`]+`$/.test(tok)) {
      runs.push(new TextRun({ text: tok.slice(1, -1), font: "Courier New" }));
    } else {
      // Plain text: scrub any leftover unmatched emphasis markers so raw
      // asterisks/underscores never leak into the Word document.
      runs.push(new TextRun(stripStrayEmphasis(tok)));
    }
  }
  return runs.length > 0 ? runs : [new TextRun(stripStrayEmphasis(text))];
}

function safeFilename(name: string): string {
  return (
    name
      .replace(/[^a-zA-Z0-9-_ ]/g, "")
      .trim()
      .replace(/\s+/g, "_")
      .slice(0, 80) || "Document"
  );
}

router.post("/docx", async (req, res) => {
  try {
    const { title, content } = (req.body ?? {}) as {
      title?: string;
      content?: string;
    };

    if (!content || typeof content !== "string" || content.trim().length === 0) {
      return res.status(400).json({ error: "content is required" });
    }

    const docTitle = (title && title.trim()) || "MyLitAi Document";

    const headerParagraph = new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: docTitle, bold: true, size: 36 })],
    });

    const metaParagraph = new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: `Generated by MyLitAi  •  ${new Date().toLocaleDateString(
            "en-GB",
            { day: "2-digit", month: "long", year: "numeric" },
          )}`,
          italics: true,
          size: 18,
          color: "666666",
        }),
      ],
    });

    const spacer = new Paragraph({ children: [new TextRun("")] });

    const doc = new Document({
      creator: "MyLitAi",
      title: docTitle,
      description: "AI-generated legal document",
      numbering: {
        config: [
          {
            reference: "default-numbering",
            levels: [
              {
                level: 0,
                format: "decimal",
                text: "%1.",
                alignment: AlignmentType.LEFT,
              },
            ],
          },
        ],
      },
      styles: {
        default: {
          document: {
            run: { font: "Calibri", size: 22 },
          },
        },
      },
      sections: [
        {
          children: [
            headerParagraph,
            metaParagraph,
            spacer,
            ...buildParagraphs(content),
          ],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    const filename = `${safeFilename(docTitle)}_${new Date()
      .toISOString()
      .slice(0, 10)}.docx`;

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    );
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${filename}"`,
    );
    res.setHeader("Content-Length", buffer.length.toString());
    return res.end(buffer);
  } catch (err) {
    logger.error({ err }, "DOCX export failed");
    return res.status(500).json({ error: "Failed to generate DOCX" });
  }
});

export default router;
