/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Verifies the manager passcode server-side and, on success, sets a signed httpOnly session cookie. Privileged manager routes require this verified session rather than a caller-supplied actingUserId.
 * @summary Verify the manager passcode and start a manager session
 */



export const ManagerLoginBody = zod.object({
  "passcode": zod.string().min(1)
})

export const ManagerLoginResponse = zod.object({
  "manager": zod.boolean(),
  "staff": zod.boolean(),
  "user": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "role": zod.enum(['manager', 'staff']),
  "title": zod.string().nullish(),
  "email": zod.string(),
  "activeStatus": zod.boolean(),
  "phone": zod.string().nullish(),
  "whatsappOptIn": zod.boolean(),
  "whatsappOptInAt": zod.coerce.date().nullish(),
  "smsOptIn": zod.boolean(),
  "smsOptInAt": zod.coerce.date().nullish()
}).optional()
})


/**
 * Verifies the shared staff passcode server-side and, on success, sets a signed httpOnly session cookie. Every API route requires a valid staff (or manager) session; this is the primary trust boundary and replaces reliance on a client-embedded shared secret.
 * @summary Verify the shared staff passcode and start a staff session
 */



export const StaffLoginBody = zod.object({
  "passcode": zod.string().min(1)
})

export const StaffLoginResponse = zod.object({
  "manager": zod.boolean(),
  "staff": zod.boolean(),
  "user": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "role": zod.enum(['manager', 'staff']),
  "title": zod.string().nullish(),
  "email": zod.string(),
  "activeStatus": zod.boolean(),
  "phone": zod.string().nullish(),
  "whatsappOptIn": zod.boolean(),
  "whatsappOptInAt": zod.coerce.date().nullish(),
  "smsOptIn": zod.boolean(),
  "smsOptInAt": zod.coerce.date().nullish()
}).optional()
})


/**
 * @summary End the current manager session
 */
export const ManagerLogoutResponse = zod.object({
  "manager": zod.boolean(),
  "staff": zod.boolean(),
  "user": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "role": zod.enum(['manager', 'staff']),
  "title": zod.string().nullish(),
  "email": zod.string(),
  "activeStatus": zod.boolean(),
  "phone": zod.string().nullish(),
  "whatsappOptIn": zod.boolean(),
  "whatsappOptInAt": zod.coerce.date().nullish(),
  "smsOptIn": zod.boolean(),
  "smsOptInAt": zod.coerce.date().nullish()
}).optional()
})


/**
 * @summary Return the current manager session status
 */
export const GetManagerSessionResponse = zod.object({
  "manager": zod.boolean(),
  "staff": zod.boolean(),
  "user": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "role": zod.enum(['manager', 'staff']),
  "title": zod.string().nullish(),
  "email": zod.string(),
  "activeStatus": zod.boolean(),
  "phone": zod.string().nullish(),
  "whatsappOptIn": zod.boolean(),
  "whatsappOptInAt": zod.coerce.date().nullish(),
  "smsOptIn": zod.boolean(),
  "smsOptInAt": zod.coerce.date().nullish()
}).optional()
})


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all users
 */
export const ListUsersResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "role": zod.enum(['manager', 'staff']),
  "title": zod.string().nullish(),
  "email": zod.string(),
  "activeStatus": zod.boolean(),
  "phone": zod.string().nullish(),
  "whatsappOptIn": zod.boolean(),
  "whatsappOptInAt": zod.coerce.date().nullish(),
  "smsOptIn": zod.boolean(),
  "smsOptInAt": zod.coerce.date().nullish()
})
export const ListUsersResponse = zod.array(ListUsersResponseItem)


/**
 * @summary Create a user
 */




export const CreateUserBody = zod.object({
  "name": zod.string().min(1),
  "role": zod.enum(['manager', 'staff']),
  "title": zod.string().nullish(),
  "email": zod.string().min(1),
  "activeStatus": zod.boolean().optional()
})


/**
 * @summary Update a user's role (manager only)
 */
export const UpdateUserParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateUserBody = zod.object({
  "role": zod.enum(['manager', 'staff']),
  "actingUserId": zod.number().nullish()
})

export const UpdateUserResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "role": zod.enum(['manager', 'staff']),
  "title": zod.string().nullish(),
  "email": zod.string(),
  "activeStatus": zod.boolean(),
  "phone": zod.string().nullish(),
  "whatsappOptIn": zod.boolean(),
  "whatsappOptInAt": zod.coerce.date().nullish(),
  "smsOptIn": zod.boolean(),
  "smsOptInAt": zod.coerce.date().nullish()
})


/**
 * @summary Update a user's phone number and SMS / WhatsApp reminder consent
 */
export const UpdateUserContactParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateUserContactBody = zod.object({
  "phone": zod.string().nullish(),
  "whatsappOptIn": zod.boolean(),
  "smsOptIn": zod.boolean(),
  "actingUserId": zod.number().nullish()
})

export const UpdateUserContactResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "role": zod.enum(['manager', 'staff']),
  "title": zod.string().nullish(),
  "email": zod.string(),
  "activeStatus": zod.boolean(),
  "phone": zod.string().nullish(),
  "whatsappOptIn": zod.boolean(),
  "whatsappOptInAt": zod.coerce.date().nullish(),
  "smsOptIn": zod.boolean(),
  "smsOptInAt": zod.coerce.date().nullish()
})


/**
 * @summary List tasks with optional filters
 */
export const ListTasksQueryParams = zod.object({
  "category": zod.enum(['urgent', 'backlog']).optional(),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']).optional(),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']).optional(),
  "ownerId": zod.coerce.number().optional(),
  "memberId": zod.coerce.number().optional().describe('Match tasks where the user is the owner OR a collaborator.'),
  "search": zod.coerce.string().optional(),
  "includeArchived": zod.coerce.boolean().optional()
})

export const ListTasksResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})
export const ListTasksResponse = zod.array(ListTasksResponseItem)


/**
 * @summary Create a task
 */



export const CreateTaskBody = zod.object({
  "title": zod.string().min(1),
  "description": zod.string().optional(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "ownerId": zod.number().nullish(),
  "createdById": zod.number().nullish(),
  "goalId": zod.number().nullish(),
  "dueAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaboratorIds": zod.array(zod.number()).optional().describe('User ids to add as collaborators on the new task.')
})


/**
 * @summary Get a single task
 */
export const GetTaskParams = zod.object({
  "id": zod.coerce.number()
})

export const GetTaskResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})


/**
 * @summary Update a task (manager edits, reassign, reason, category, due date)
 */
export const UpdateTaskParams = zod.object({
  "id": zod.coerce.number()
})




export const UpdateTaskBody = zod.object({
  "title": zod.string().min(1).optional(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']).optional(),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']).optional(),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']).optional(),
  "ownerId": zod.number().nullish(),
  "goalId": zod.number().nullish(),
  "dueAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "actingUserId": zod.number().nullish()
})

export const UpdateTaskResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})


/**
 * @summary Archive a task (soft delete, manager only)
 */
export const ArchiveTaskParams = zod.object({
  "id": zod.coerce.number()
})

export const ArchiveTaskBody = zod.object({
  "actingUserId": zod.number().nullish()
})

export const ArchiveTaskResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})


/**
 * @summary Acknowledge an urgent task
 */
export const AcknowledgeTaskParams = zod.object({
  "id": zod.coerce.number()
})

export const AcknowledgeTaskBody = zod.object({
  "actingUserId": zod.number().nullish()
})

export const AcknowledgeTaskResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})


/**
 * @summary Change task status (start, block, unblock, mark done)
 */
export const ChangeTaskStatusParams = zod.object({
  "id": zod.coerce.number()
})

export const ChangeTaskStatusBody = zod.object({
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "note": zod.string().optional(),
  "actingUserId": zod.number().nullish()
})

export const ChangeTaskStatusResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})


/**
 * @summary Nudge the task owner
 */
export const NudgeTaskParams = zod.object({
  "id": zod.coerce.number()
})

export const NudgeTaskBody = zod.object({
  "actingUserId": zod.number().nullish()
})

export const NudgeTaskResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})


/**
 * @summary List notes for a task
 */
export const ListTaskNotesParams = zod.object({
  "id": zod.coerce.number()
})

export const ListTaskNotesResponseItem = zod.object({
  "id": zod.number(),
  "taskId": zod.number(),
  "authorId": zod.number().nullish(),
  "authorName": zod.string().nullish(),
  "body": zod.string(),
  "createdAt": zod.coerce.date()
})
export const ListTaskNotesResponse = zod.array(ListTaskNotesResponseItem)


/**
 * @summary Add a note to a task
 */
export const AddTaskNoteParams = zod.object({
  "id": zod.coerce.number()
})




export const AddTaskNoteBody = zod.object({
  "body": zod.string().min(1),
  "authorId": zod.number().nullish()
})


/**
 * @summary List the audit trail of edits/reassignments for a task
 */
export const ListTaskActivityParams = zod.object({
  "id": zod.coerce.number()
})

export const ListTaskActivityResponseItem = zod.object({
  "id": zod.number(),
  "taskId": zod.number(),
  "actorId": zod.number().nullish(),
  "actorName": zod.string().nullish(),
  "action": zod.string().describe('Canonical action key (e.g. reassigned, status_changed, edited, archived, collaborator_added).'),
  "meta": zod.record(zod.string(), zod.unknown()).nullish().describe('Before\/after context for the action, rendered bilingually on the client.'),
  "createdAt": zod.coerce.date()
})
export const ListTaskActivityResponse = zod.array(ListTaskActivityResponseItem)


/**
 * @summary List completion attempts logged for a task
 */
export const ListTaskAttemptsParams = zod.object({
  "id": zod.coerce.number()
})

export const ListTaskAttemptsResponseItem = zod.object({
  "id": zod.number(),
  "taskId": zod.number(),
  "authorId": zod.number().nullish(),
  "authorName": zod.string().nullish(),
  "body": zod.string(),
  "source": zod.enum(['text', 'voice']),
  "createdAt": zod.coerce.date()
})
export const ListTaskAttemptsResponse = zod.array(ListTaskAttemptsResponseItem)


/**
 * @summary Log a completion attempt (typed text or voice recording)
 */
export const AddTaskAttemptParams = zod.object({
  "id": zod.coerce.number()
})

export const AddTaskAttemptBody = zod.object({
  "body": zod.string().nullish().describe('Typed attempt text. Provide this OR audioBase64.'),
  "audioBase64": zod.string().nullish().describe('Base64-encoded audio of a spoken attempt (no data prefix). Transcribed server-side.'),
  "lang": zod.string().nullish(),
  "authorId": zod.number().nullish()
})


/**
 * @summary List evidence files uploaded for a task
 */
export const ListTaskEvidenceParams = zod.object({
  "id": zod.coerce.number()
})

export const ListTaskEvidenceResponseItem = zod.object({
  "id": zod.number(),
  "taskId": zod.number(),
  "authorId": zod.number().nullish(),
  "authorName": zod.string().nullish(),
  "objectPath": zod.string(),
  "fileName": zod.string(),
  "contentType": zod.string().nullish(),
  "fileSize": zod.number().nullish(),
  "createdAt": zod.coerce.date()
})
export const ListTaskEvidenceResponse = zod.array(ListTaskEvidenceResponseItem)


/**
 * @summary Attach an uploaded evidence file to a task
 */
export const AddTaskEvidenceParams = zod.object({
  "id": zod.coerce.number()
})





export const AddTaskEvidenceBody = zod.object({
  "objectPath": zod.string().min(1).describe('Object path returned by the upload endpoint (e.g. \/objects\/uploads\/uuid).'),
  "fileName": zod.string().min(1),
  "contentType": zod.string().nullish(),
  "fileSize": zod.number().nullish(),
  "authorId": zod.number().nullish()
})


/**
 * @summary Remove an evidence file from a task
 */
export const DeleteTaskEvidenceParams = zod.object({
  "id": zod.coerce.number(),
  "evidenceId": zod.coerce.number()
})

export const DeleteTaskEvidenceBody = zod.object({
  "actingUserId": zod.number().nullish()
})


/**
 * @summary Get the manager quality/creativity assessment for a task
 */
export const GetTaskAssessmentParams = zod.object({
  "id": zod.coerce.number()
})

export const getTaskAssessmentResponseOneQualityScoreMax = 5;

export const getTaskAssessmentResponseOneCreativityScoreMax = 5;



export const GetTaskAssessmentResponse = zod.union([zod.object({
  "id": zod.number(),
  "taskId": zod.number(),
  "raterId": zod.number().nullish(),
  "raterName": zod.string().nullish(),
  "qualityScore": zod.number().min(1).max(getTaskAssessmentResponseOneQualityScoreMax),
  "creativityScore": zod.number().min(1).max(getTaskAssessmentResponseOneCreativityScoreMax),
  "note": zod.string().nullish(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
}),zod.null()])


/**
 * @summary Create or update a manager quality/creativity assessment (manager only, completed tasks)
 */
export const UpsertTaskAssessmentParams = zod.object({
  "id": zod.coerce.number()
})

export const upsertTaskAssessmentBodyQualityScoreMax = 5;

export const upsertTaskAssessmentBodyCreativityScoreMax = 5;



export const UpsertTaskAssessmentBody = zod.object({
  "actingUserId": zod.number().describe('The id of the manager submitting the assessment.'),
  "qualityScore": zod.number().min(1).max(upsertTaskAssessmentBodyQualityScoreMax).describe('How well the task was completed (1 = poor, 5 = excellent).'),
  "creativityScore": zod.number().min(1).max(upsertTaskAssessmentBodyCreativityScoreMax).describe('How creative the approach was (1 = routine, 5 = highly creative).'),
  "note": zod.string().nullish().describe('Optional justification referencing the staff\'s attempts and evidence.')
})

export const upsertTaskAssessmentResponseQualityScoreMax = 5;

export const upsertTaskAssessmentResponseCreativityScoreMax = 5;



export const UpsertTaskAssessmentResponse = zod.object({
  "id": zod.number(),
  "taskId": zod.number(),
  "raterId": zod.number().nullish(),
  "raterName": zod.string().nullish(),
  "qualityScore": zod.number().min(1).max(upsertTaskAssessmentResponseQualityScoreMax),
  "creativityScore": zod.number().min(1).max(upsertTaskAssessmentResponseCreativityScoreMax),
  "note": zod.string().nullish(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary List the collaborators on a task
 */
export const ListTaskCollaboratorsParams = zod.object({
  "id": zod.coerce.number()
})

export const ListTaskCollaboratorsResponseItem = zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})
export const ListTaskCollaboratorsResponse = zod.array(ListTaskCollaboratorsResponseItem)


/**
 * @summary Add a collaborator to a task
 */
export const AddTaskCollaboratorParams = zod.object({
  "id": zod.coerce.number()
})

export const AddTaskCollaboratorBody = zod.object({
  "userId": zod.number(),
  "actingUserId": zod.number().nullish()
})

export const AddTaskCollaboratorResponseItem = zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})
export const AddTaskCollaboratorResponse = zod.array(AddTaskCollaboratorResponseItem)


/**
 * @summary Remove a collaborator from a task
 */
export const RemoveTaskCollaboratorParams = zod.object({
  "id": zod.coerce.number(),
  "userId": zod.coerce.number()
})

export const RemoveTaskCollaboratorBody = zod.object({
  "actingUserId": zod.number().nullish()
})

export const RemoveTaskCollaboratorResponseItem = zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})
export const RemoveTaskCollaboratorResponse = zod.array(RemoveTaskCollaboratorResponseItem)


/**
 * @summary Performance leaderboard ranking staff by speed, throughput, quality and creativity
 */
export const GetRecognitionLeaderboardResponse = zod.object({
  "generatedAt": zod.coerce.date(),
  "fastThresholdDays": zod.number().describe('Team median turnaround in days; completions faster than this count as \"fast\".'),
  "entries": zod.array(zod.object({
  "userId": zod.number(),
  "userName": zod.string(),
  "role": zod.string(),
  "completedCount": zod.number().describe('Number of completed (done) tasks.'),
  "onTimeCount": zod.number().optional().describe('Completed tasks finished on or before their deadline.'),
  "speedScore": zod.number().describe('Blended speed score 0-100 (deadline margin, turnaround, vs team average).'),
  "throughputScore": zod.number().describe('Volume of completed work relative to the team, 0-100.'),
  "qualityScore": zod.number().nullish().describe('Average manager quality rating scaled to 0-100, or null if unrated.'),
  "creativityScore": zod.number().nullish().describe('Average manager creativity rating scaled to 0-100, or null if unrated.'),
  "overallScore": zod.number().describe('Weighted overall recognition score, 0-100.'),
  "assessedCount": zod.number().describe('Number of completed tasks that have a manager assessment.'),
  "bonusEligible": zod.boolean(),
  "promotionCandidate": zod.boolean()
}))
})


/**
 * @summary Manager-only bonus eligibility and promotion (naik pangkat) recommendations
 */
export const GetRecognitionRecommendationsQueryParams = zod.object({
  "actingUserId": zod.coerce.number().describe('The id of the manager requesting recommendations.')
})

export const GetRecognitionRecommendationsResponse = zod.object({
  "generatedAt": zod.coerce.date(),
  "bonus": zod.array(zod.object({
  "userId": zod.number(),
  "userName": zod.string(),
  "role": zod.string(),
  "overallScore": zod.number(),
  "reasons": zod.array(zod.string()).describe('Human-readable justifications for the recommendation.')
})),
  "promotion": zod.array(zod.object({
  "userId": zod.number(),
  "userName": zod.string(),
  "role": zod.string(),
  "overallScore": zod.number(),
  "reasons": zod.array(zod.string()).describe('Human-readable justifications for the recommendation.')
}))
})


/**
 * Returns a presigned GCS URL for direct upload. The client sends JSON
metadata here, then uploads the file directly to the returned URL.

 * @summary Request a presigned URL for file upload
 */





export const RequestUploadUrlBody = zod.object({
  "actingUserId": zod.number().describe('ID of the authenticated user requesting the upload URL.'),
  "name": zod.string().min(1).describe('Original file name.'),
  "size": zod.number().min(1).describe('File size in bytes.'),
  "contentType": zod.string().min(1).describe('MIME type of the file (e.g. image\/jpeg).')
})






export const RequestUploadUrlResponse = zod.object({
  "uploadURL": zod.string().url().describe('Presigned GCS URL for PUT upload.'),
  "objectPath": zod.string().describe('Normalized object path (e.g. \/objects\/uploads\/uuid).'),
  "metadata": zod.object({
  "name": zod.string().min(1).describe('Original file name.'),
  "size": zod.number().min(1).describe('File size in bytes.'),
  "contentType": zod.string().min(1).describe('MIME type of the file (e.g. image\/jpeg).')
}).optional()
})


/**
 * @summary Serve a public asset from PUBLIC_OBJECT_SEARCH_PATHS
 */
export const GetPublicObjectParams = zod.object({
  "filePath": zod.coerce.string().describe('Relative file path within the public search paths.')
})


/**
 * Requires an `actingUserId` query parameter with a valid user ID.
Anonymous requests are rejected with 401.

 * @summary Serve an object entity from PRIVATE_OBJECT_DIR
 */
export const GetStorageObjectParams = zod.object({
  "objectPath": zod.coerce.string().describe('Object path within the private object dir (e.g. `uploads\/some-uuid`).')
})


/**
 * @summary Manager dashboard metrics
 */
export const GetDashboardResponse = zod.object({
  "totalUrgent": zod.number(),
  "unacknowledgedUrgent": zod.number(),
  "staleBacklog": zod.number(),
  "dueToday": zod.number(),
  "overdue": zod.number(),
  "blockedNoNote": zod.number(),
  "avgAcknowledgeMinutes": zod.number().nullable(),
  "avgCompleteMinutes": zod.number().nullable(),
  "tasksByOwner": zod.array(zod.object({
  "ownerId": zod.number().nullable(),
  "ownerName": zod.string(),
  "total": zod.number(),
  "active": zod.number(),
  "urgent": zod.number(),
  "overdue": zod.number()
})),
  "tasksByStatus": zod.array(zod.object({
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "count": zod.number()
})),
  "completionTrend": zod.array(zod.object({
  "date": zod.string(),
  "completed": zod.number()
}))
})


/**
 * @summary Daily backlog digest
 */
export const GetDigestResponse = zod.object({
  "newlyStale": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "noOwner": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "approachingDue": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "inactiveOverWeek": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "recommended": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
}))
})


/**
 * @summary Org-wide recent task activity (manager only)
 */
export const GetRecentActivityQueryParams = zod.object({
  "limit": zod.coerce.number().optional(),
  "cursorCreatedAt": zod.date().optional().describe('Keyset cursor — the createdAt of the last item from the previous page. Omit for the first page.'),
  "cursorId": zod.coerce.number().optional().describe('Keyset cursor — the id of the last item from the previous page. Must accompany cursorCreatedAt.'),
  "actor": zod.coerce.string().optional().describe('Filter by actor — a numeric user id, or the literal \"system\" for automated entries.'),
  "actions": zod.coerce.string().optional().describe('Comma-separated canonical action keys to include (e.g. \"status_changed,reassigned\"). Omit for all actions.'),
  "export": zod.coerce.boolean().optional().describe('When true, returns the full filtered range (unpaginated, up to a safe maximum) for spreadsheet export instead of a single page.'),
  "from": zod.coerce.string().optional().describe('ISO 8601 timestamp — only include entries created at or after this instant.'),
  "to": zod.coerce.string().optional().describe('ISO 8601 timestamp — only include entries created strictly before this instant.')
})

export const GetRecentActivityResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number(),
  "taskId": zod.number(),
  "taskTitle": zod.string().nullish(),
  "actorId": zod.number().nullish(),
  "actorName": zod.string().nullish(),
  "action": zod.string().describe('Canonical action key (e.g. reassigned, status_changed, edited, archived, collaborator_added).'),
  "meta": zod.record(zod.string(), zod.unknown()).nullish().describe('Before\/after context for the action, rendered bilingually on the client.'),
  "createdAt": zod.coerce.date()
})),
  "hasMore": zod.boolean()
})


/**
 * @summary List goals with KPIs and rolled-up deliverables
 */
export const ListGoalsQueryParams = zod.object({
  "includeArchived": zod.coerce.boolean().optional()
})

export const ListGoalsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "timeframe": zod.string().nullish(),
  "status": zod.enum(['active', 'achieved', 'paused']),
  "health": zod.enum(['on_track', 'at_risk', 'achieved']),
  "archived": zod.boolean(),
  "kpis": zod.array(zod.object({
  "id": zod.number(),
  "goalId": zod.number(),
  "name": zod.string(),
  "unit": zod.string().nullish(),
  "targetValue": zod.number(),
  "currentValue": zod.number(),
  "direction": zod.enum(['up', 'down']),
  "attainmentPct": zod.number(),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})),
  "deliverableStats": zod.object({
  "total": zod.number(),
  "done": zod.number(),
  "blocked": zod.number(),
  "overdue": zod.number(),
  "urgent": zod.number(),
  "progressPct": zod.number()
}),
  "deliverables": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})
export const ListGoalsResponse = zod.array(ListGoalsResponseItem)


/**
 * @summary Create a goal (manager only)
 */



export const CreateGoalBody = zod.object({
  "title": zod.string().min(1),
  "description": zod.string().nullish(),
  "ownerId": zod.number().nullish(),
  "timeframe": zod.string().nullish(),
  "status": zod.enum(['active', 'achieved', 'paused']).optional(),
  "actingUserId": zod.number().nullish()
})


/**
 * @summary Draft a goal and KPIs from a free-text prompt (manager only)
 */



export const AiBuildGoalBody = zod.object({
  "prompt": zod.string().min(1),
  "lang": zod.enum(['en', 'ms']),
  "actingUserId": zod.number().nullish()
})

export const AiBuildGoalResponse = zod.object({
  "title": zod.string(),
  "description": zod.string().nullish(),
  "timeframe": zod.string().nullish(),
  "kpis": zod.array(zod.object({
  "name": zod.string(),
  "unit": zod.string().nullish(),
  "targetValue": zod.number(),
  "currentValue": zod.number().optional(),
  "direction": zod.enum(['up', 'down'])
}))
})


/**
 * @summary Get a single goal
 */
export const GetGoalParams = zod.object({
  "id": zod.coerce.number()
})

export const GetGoalResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "timeframe": zod.string().nullish(),
  "status": zod.enum(['active', 'achieved', 'paused']),
  "health": zod.enum(['on_track', 'at_risk', 'achieved']),
  "archived": zod.boolean(),
  "kpis": zod.array(zod.object({
  "id": zod.number(),
  "goalId": zod.number(),
  "name": zod.string(),
  "unit": zod.string().nullish(),
  "targetValue": zod.number(),
  "currentValue": zod.number(),
  "direction": zod.enum(['up', 'down']),
  "attainmentPct": zod.number(),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})),
  "deliverableStats": zod.object({
  "total": zod.number(),
  "done": zod.number(),
  "blocked": zod.number(),
  "overdue": zod.number(),
  "urgent": zod.number(),
  "progressPct": zod.number()
}),
  "deliverables": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})


/**
 * @summary Update a goal (manager only)
 */
export const UpdateGoalParams = zod.object({
  "id": zod.coerce.number()
})




export const UpdateGoalBody = zod.object({
  "title": zod.string().min(1).optional(),
  "description": zod.string().nullish(),
  "ownerId": zod.number().nullish(),
  "timeframe": zod.string().nullish(),
  "status": zod.enum(['active', 'achieved', 'paused']).optional(),
  "actingUserId": zod.number().nullish()
})

export const UpdateGoalResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "timeframe": zod.string().nullish(),
  "status": zod.enum(['active', 'achieved', 'paused']),
  "health": zod.enum(['on_track', 'at_risk', 'achieved']),
  "archived": zod.boolean(),
  "kpis": zod.array(zod.object({
  "id": zod.number(),
  "goalId": zod.number(),
  "name": zod.string(),
  "unit": zod.string().nullish(),
  "targetValue": zod.number(),
  "currentValue": zod.number(),
  "direction": zod.enum(['up', 'down']),
  "attainmentPct": zod.number(),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})),
  "deliverableStats": zod.object({
  "total": zod.number(),
  "done": zod.number(),
  "blocked": zod.number(),
  "overdue": zod.number(),
  "urgent": zod.number(),
  "progressPct": zod.number()
}),
  "deliverables": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})


/**
 * @summary Archive a goal (manager only)
 */
export const ArchiveGoalParams = zod.object({
  "id": zod.coerce.number()
})

export const ArchiveGoalBody = zod.object({
  "actingUserId": zod.number().nullish()
})

export const ArchiveGoalResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "timeframe": zod.string().nullish(),
  "status": zod.enum(['active', 'achieved', 'paused']),
  "health": zod.enum(['on_track', 'at_risk', 'achieved']),
  "archived": zod.boolean(),
  "kpis": zod.array(zod.object({
  "id": zod.number(),
  "goalId": zod.number(),
  "name": zod.string(),
  "unit": zod.string().nullish(),
  "targetValue": zod.number(),
  "currentValue": zod.number(),
  "direction": zod.enum(['up', 'down']),
  "attainmentPct": zod.number(),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})),
  "deliverableStats": zod.object({
  "total": zod.number(),
  "done": zod.number(),
  "blocked": zod.number(),
  "overdue": zod.number(),
  "urgent": zod.number(),
  "progressPct": zod.number()
}),
  "deliverables": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})


/**
 * @summary Add a KPI to a goal (manager only)
 */
export const AddKpiParams = zod.object({
  "id": zod.coerce.number()
})




export const AddKpiBody = zod.object({
  "name": zod.string().min(1),
  "unit": zod.string().nullish(),
  "targetValue": zod.number(),
  "currentValue": zod.number().optional(),
  "direction": zod.enum(['up', 'down']).optional(),
  "actingUserId": zod.number().nullish()
})

export const AddKpiResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "timeframe": zod.string().nullish(),
  "status": zod.enum(['active', 'achieved', 'paused']),
  "health": zod.enum(['on_track', 'at_risk', 'achieved']),
  "archived": zod.boolean(),
  "kpis": zod.array(zod.object({
  "id": zod.number(),
  "goalId": zod.number(),
  "name": zod.string(),
  "unit": zod.string().nullish(),
  "targetValue": zod.number(),
  "currentValue": zod.number(),
  "direction": zod.enum(['up', 'down']),
  "attainmentPct": zod.number(),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})),
  "deliverableStats": zod.object({
  "total": zod.number(),
  "done": zod.number(),
  "blocked": zod.number(),
  "overdue": zod.number(),
  "urgent": zod.number(),
  "progressPct": zod.number()
}),
  "deliverables": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})


/**
 * @summary Update a KPI, including its current value (manager only)
 */
export const UpdateKpiParams = zod.object({
  "id": zod.coerce.number(),
  "kpiId": zod.coerce.number()
})




export const UpdateKpiBody = zod.object({
  "name": zod.string().min(1).optional(),
  "unit": zod.string().nullish(),
  "targetValue": zod.number().optional(),
  "currentValue": zod.number().optional(),
  "direction": zod.enum(['up', 'down']).optional(),
  "actingUserId": zod.number().nullish()
})

export const UpdateKpiResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "timeframe": zod.string().nullish(),
  "status": zod.enum(['active', 'achieved', 'paused']),
  "health": zod.enum(['on_track', 'at_risk', 'achieved']),
  "archived": zod.boolean(),
  "kpis": zod.array(zod.object({
  "id": zod.number(),
  "goalId": zod.number(),
  "name": zod.string(),
  "unit": zod.string().nullish(),
  "targetValue": zod.number(),
  "currentValue": zod.number(),
  "direction": zod.enum(['up', 'down']),
  "attainmentPct": zod.number(),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})),
  "deliverableStats": zod.object({
  "total": zod.number(),
  "done": zod.number(),
  "blocked": zod.number(),
  "overdue": zod.number(),
  "urgent": zod.number(),
  "progressPct": zod.number()
}),
  "deliverables": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})


/**
 * @summary Delete a KPI (manager only)
 */
export const DeleteKpiParams = zod.object({
  "id": zod.coerce.number(),
  "kpiId": zod.coerce.number()
})

export const DeleteKpiBody = zod.object({
  "actingUserId": zod.number().nullish()
})

export const DeleteKpiResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "timeframe": zod.string().nullish(),
  "status": zod.enum(['active', 'achieved', 'paused']),
  "health": zod.enum(['on_track', 'at_risk', 'achieved']),
  "archived": zod.boolean(),
  "kpis": zod.array(zod.object({
  "id": zod.number(),
  "goalId": zod.number(),
  "name": zod.string(),
  "unit": zod.string().nullish(),
  "targetValue": zod.number(),
  "currentValue": zod.number(),
  "direction": zod.enum(['up', 'down']),
  "attainmentPct": zod.number(),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})),
  "deliverableStats": zod.object({
  "total": zod.number(),
  "done": zod.number(),
  "blocked": zod.number(),
  "overdue": zod.number(),
  "urgent": zod.number(),
  "progressPct": zod.number()
}),
  "deliverables": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "createdAt": zod.coerce.date(),
  "lastUpdatedAt": zod.coerce.date()
})


/**
 * @summary Generate an AI manager briefing of the whole team's task state
 */
export const GenerateAiBriefingBody = zod.object({
  "actingUserId": zod.number(),
  "lang": zod.enum(['en', 'ms'])
})

export const GenerateAiBriefingResponse = zod.object({
  "generatedAt": zod.coerce.date(),
  "headline": zod.string(),
  "summary": zod.string(),
  "risks": zod.array(zod.object({
  "severity": zod.enum(['high', 'medium', 'low']),
  "title": zod.string(),
  "detail": zod.string()
})),
  "recommendations": zod.array(zod.object({
  "action": zod.string(),
  "rationale": zod.string(),
  "taskId": zod.number().nullish(),
  "taskTitle": zod.string().nullish(),
  "ownerName": zod.string().nullish()
}))
})


/**
 * @summary Suggest category, reason, and best owner for a new task
 */



export const AiTriageTaskBody = zod.object({
  "title": zod.string().min(1),
  "description": zod.string().nullish(),
  "lang": zod.enum(['en', 'ms'])
})

export const AiTriageTaskResponse = zod.object({
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "suggestedOwnerId": zod.number().nullish(),
  "suggestedOwnerName": zod.string().nullish(),
  "rationale": zod.string(),
  "confidence": zod.enum(['high', 'medium', 'low']).optional()
})


/**
 * @summary List recorded meetings
 */
export const ListMeetingsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "lang": zod.enum(['en', 'ms']),
  "segments": zod.array(zod.object({
  "speaker": zod.string(),
  "text": zod.string()
})),
  "rawTranscript": zod.string(),
  "minutes": zod.union([zod.object({
  "title": zod.string(),
  "summary": zod.string(),
  "attendees": zod.array(zod.string()),
  "agenda": zod.array(zod.object({
  "topic": zod.string(),
  "discussion": zod.string(),
  "decisions": zod.array(zod.string())
})),
  "decisions": zod.array(zod.string()),
  "actionItems": zod.array(zod.object({
  "text": zod.string(),
  "owner": zod.string().nullable(),
  "taskId": zod.number().nullable()
}))
}),zod.null()]),
  "createdById": zod.number().nullable(),
  "createdByName": zod.string().nullable(),
  "createdAt": zod.coerce.date()
})
export const ListMeetingsResponse = zod.array(ListMeetingsResponseItem)


/**
 * @summary Generate structured minutes from a transcript and persist the meeting
 */
export const CreateMeetingBody = zod.object({
  "title": zod.string().nullish(),
  "lang": zod.enum(['en', 'ms']),
  "segments": zod.array(zod.object({
  "speaker": zod.string(),
  "text": zod.string()
})),
  "rawTranscript": zod.string(),
  "actingUserId": zod.number().nullish()
})


/**
 * @summary Transcribe meeting audio with speaker diarization
 */
export const TranscribeMeetingBody = zod.object({
  "audioBase64": zod.string(),
  "mimeType": zod.string(),
  "actingUserId": zod.number()
})

export const TranscribeMeetingResponse = zod.object({
  "segments": zod.array(zod.object({
  "speaker": zod.string(),
  "text": zod.string()
})),
  "rawTranscript": zod.string()
})


/**
 * @summary Get one meeting
 */
export const GetMeetingParams = zod.object({
  "id": zod.coerce.number()
})

export const GetMeetingResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "lang": zod.enum(['en', 'ms']),
  "segments": zod.array(zod.object({
  "speaker": zod.string(),
  "text": zod.string()
})),
  "rawTranscript": zod.string(),
  "minutes": zod.union([zod.object({
  "title": zod.string(),
  "summary": zod.string(),
  "attendees": zod.array(zod.string()),
  "agenda": zod.array(zod.object({
  "topic": zod.string(),
  "discussion": zod.string(),
  "decisions": zod.array(zod.string())
})),
  "decisions": zod.array(zod.string()),
  "actionItems": zod.array(zod.object({
  "text": zod.string(),
  "owner": zod.string().nullable(),
  "taskId": zod.number().nullable()
}))
}),zod.null()]),
  "createdById": zod.number().nullable(),
  "createdByName": zod.string().nullable(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Delete a meeting (manager only)
 */
export const DeleteMeetingParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteMeetingBody = zod.object({
  "actingUserId": zod.number().nullish()
})


/**
 * @summary Create TaskRadar tasks from selected meeting action items
 */
export const CreateMeetingTasksParams = zod.object({
  "id": zod.coerce.number()
})

export const CreateMeetingTasksBody = zod.object({
  "actingUserId": zod.number().nullish(),
  "items": zod.array(zod.object({
  "actionItemIndex": zod.number(),
  "title": zod.string().nullish(),
  "ownerId": zod.number().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "dueAt": zod.coerce.date().nullish()
}))
})

export const CreateMeetingTasksResponse = zod.object({
  "created": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
})),
  "meeting": zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "lang": zod.enum(['en', 'ms']),
  "segments": zod.array(zod.object({
  "speaker": zod.string(),
  "text": zod.string()
})),
  "rawTranscript": zod.string(),
  "minutes": zod.union([zod.object({
  "title": zod.string(),
  "summary": zod.string(),
  "attendees": zod.array(zod.string()),
  "agenda": zod.array(zod.object({
  "topic": zod.string(),
  "discussion": zod.string(),
  "decisions": zod.array(zod.string())
})),
  "decisions": zod.array(zod.string()),
  "actionItems": zod.array(zod.object({
  "text": zod.string(),
  "owner": zod.string().nullable(),
  "taskId": zod.number().nullable()
}))
}),zod.null()]),
  "createdById": zod.number().nullable(),
  "createdByName": zod.string().nullable(),
  "createdAt": zod.coerce.date()
})
})


/**
 * @summary Export meeting minutes as a Word (.docx) document
 */
export const ExportMeetingDocxParams = zod.object({
  "id": zod.coerce.number()
})

export const ExportMeetingDocxResponse = zod.object({
  "filename": zod.string(),
  "mimeType": zod.string(),
  "base64": zod.string()
})


/**
 * @summary Export meeting minutes to a Google Doc
 */
export const ExportMeetingGoogleDocParams = zod.object({
  "id": zod.coerce.number()
})

export const ExportMeetingGoogleDocResponse = zod.object({
  "url": zod.string(),
  "title": zod.string()
})


/**
 * @summary Transcribe a voice instruction and draft an assigned task
 */
export const ParseVoiceInstructionBody = zod.object({
  "audioBase64": zod.string(),
  "mimeType": zod.string(),
  "lang": zod.enum(['en', 'ms']),
  "actingUserId": zod.number().nullish()
})

export const ParseVoiceInstructionResponse = zod.object({
  "transcript": zod.string(),
  "draft": zod.object({
  "title": zod.string(),
  "description": zod.string().nullish(),
  "suggestedOwnerId": zod.number().nullish(),
  "suggestedOwnerName": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "dueAt": zod.coerce.date().nullish(),
  "sourceQuote": zod.string().nullish()
}),
  "assistantReply": zod.string(),
  "missing": zod.array(zod.string())
})


/**
 * @summary Convert a WhatsApp (or other) chat screenshot into task drafts
 */
export const IngestScreenshotBody = zod.object({
  "imageBase64": zod.string(),
  "mimeType": zod.string(),
  "lang": zod.enum(['en', 'ms']),
  "actingUserId": zod.number()
})

export const IngestScreenshotResponse = zod.object({
  "source": zod.string(),
  "drafts": zod.array(zod.object({
  "title": zod.string(),
  "description": zod.string().nullish(),
  "suggestedOwnerId": zod.number().nullish(),
  "suggestedOwnerName": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "dueAt": zod.coerce.date().nullish(),
  "sourceQuote": zod.string().nullish()
})),
  "note": zod.string().nullish()
})


/**
 * @summary Pull recent Gmail messages and convert them into task drafts
 */
export const IngestGmailBody = zod.object({
  "lang": zod.enum(['en', 'ms']),
  "max": zod.number().nullish(),
  "actingUserId": zod.number()
})

export const IngestGmailResponse = zod.object({
  "source": zod.string(),
  "drafts": zod.array(zod.object({
  "title": zod.string(),
  "description": zod.string().nullish(),
  "suggestedOwnerId": zod.number().nullish(),
  "suggestedOwnerName": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "dueAt": zod.coerce.date().nullish(),
  "sourceQuote": zod.string().nullish()
})),
  "note": zod.string().nullish()
})


/**
 * @summary Convert an uploaded PDF or Word document into task drafts
 */
export const IngestDocumentBody = zod.object({
  "fileBase64": zod.string(),
  "mimeType": zod.string(),
  "filename": zod.string(),
  "lang": zod.enum(['en', 'ms']),
  "actingUserId": zod.number()
})

export const IngestDocumentResponse = zod.object({
  "source": zod.string(),
  "drafts": zod.array(zod.object({
  "title": zod.string(),
  "description": zod.string().nullish(),
  "suggestedOwnerId": zod.number().nullish(),
  "suggestedOwnerName": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "dueAt": zod.coerce.date().nullish(),
  "sourceQuote": zod.string().nullish()
})),
  "note": zod.string().nullish()
})


/**
 * @summary Create TaskRadar tasks from confirmed drafts
 */
export const CreateTasksFromDraftsBody = zod.object({
  "actingUserId": zod.number().nullish(),
  "drafts": zod.array(zod.object({
  "title": zod.string(),
  "description": zod.string().nullish(),
  "suggestedOwnerId": zod.number().nullish(),
  "suggestedOwnerName": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "dueAt": zod.coerce.date().nullish(),
  "sourceQuote": zod.string().nullish()
}))
})

export const CreateTasksFromDraftsResponse = zod.object({
  "created": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "category": zod.enum(['urgent', 'backlog']),
  "reason": zod.enum(['partner', 'compliance', 'manager', 'client', 'internal', 'finance', 'other']),
  "status": zod.enum(['todo', 'acknowledged', 'in_progress', 'blocked', 'done']),
  "ownerId": zod.number().nullish(),
  "ownerName": zod.string().nullish(),
  "createdById": zod.number().nullish(),
  "createdByName": zod.string().nullish(),
  "goalId": zod.number().nullish(),
  "goalTitle": zod.string().nullish(),
  "priorityScore": zod.number(),
  "staleFlag": zod.boolean(),
  "criticalFlag": zod.boolean(),
  "archived": zod.boolean(),
  "latestNote": zod.string().nullish(),
  "noteCount": zod.number(),
  "createdAt": zod.coerce.date(),
  "dueAt": zod.coerce.date().nullish(),
  "acknowledgedAt": zod.coerce.date().nullish(),
  "lastUpdatedAt": zod.coerce.date(),
  "lastNudgedAt": zod.coerce.date().nullish(),
  "positionLevel": zod.string().nullish(),
  "actionVerb": zod.string().nullish(),
  "qualityStandard": zod.string().nullish(),
  "natureOfWork": zod.string().nullish(),
  "businessUnit": zod.string().nullish(),
  "deliverable": zod.string().nullish(),
  "collaborators": zod.array(zod.object({
  "userId": zod.number(),
  "name": zod.string().nullish()
})).optional()
}))
})


