export function TermsPrivacy() {
  return (
    <div className="py-16 px-6 lg:px-8 max-w-4xl mx-auto space-y-16">
      <section id="terms" className="scroll-mt-8">
        <h2 className="font-serif text-3xl font-bold mb-6 text-foreground">Terms of Service</h2>
        <div className="space-y-5 text-muted-foreground leading-relaxed text-sm">
          <p>
            <strong className="text-foreground">Last updated: June 2025.</strong> These Terms of Service govern your access to and use of the AI Portals platform (&ldquo;Platform&rdquo;), operated by Shahrul Mizan Ismail (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;). By purchasing a subscription or accessing any AI Portal, you agree to these terms.
          </p>

          <div>
            <h3 className="font-semibold text-foreground mb-2">1. Subscriptions and Access</h3>
            <p>
              Each subscription grants one (1) named user access to the specified AI Portal(s). Individual plans (Bundle, Single, and Standard) are billed monthly on a recurring basis and continue until cancelled. Firm, corporate, and academic bundles are supplied as one (1) year subscriptions from the date of activation. Subscriptions are non-transferable. Bundle subscriptions cover all portals listed at the time of purchase and any updates released during the subscription period. Pre-order subscriptions will be activated upon portal launch; the subscription term begins on the activation date.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">2. Payment</h3>
            <p>
              Payment for individual subscriptions is processed securely by card through Stripe, our third-party payment processor; your subscription activates automatically once payment is confirmed and is billed on a recurring basis until cancelled. Firm, corporate, and academic bundles may be arranged directly with us. We reserve the right to refuse or cancel a subscription order at our sole discretion. All prices are in US Dollars (USD) and are inclusive of applicable taxes unless stated otherwise.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">3. Refund Policy</h3>
            <p>
              We do not offer refunds on digital subscriptions once access has been activated. If you experience a technical issue preventing access, please contact us via WhatsApp (+60 17-367 8484) or email (support@aiportals.my) within 7 days of purchase and we will work to resolve it. Pre-orders that are cancelled before launch will be refunded in full.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">4. Permitted Use</h3>
            <p>
              The Platform is for your personal professional reference use only. You may not share, resell, sublicense, or distribute your access credentials or the content generated by the Platform to any third party. Firm and institutional bundles permit use only by the number of named users specified in the subscription.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">5. Accuracy and Disclaimer</h3>
            <p>
              The AI Portals are reference tools intended to assist legal practitioners. They do not constitute legal advice. All outputs should be independently verified before reliance. We make no warranty as to the accuracy, completeness, or fitness for a particular purpose of any information provided by the Platform. Use of the Platform does not create a solicitor-client relationship.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">6. Intellectual Property</h3>
            <p>
              All content, curated knowledge bases, software, and materials on the Platform are the intellectual property of AI Portals and Shahrul Mizan Ismail. You may not reproduce, modify, or distribute any part of the Platform without our prior written consent.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">7. Governing Law</h3>
            <p>
              These Terms are governed by the laws of Malaysia. Any disputes shall be subject to the exclusive jurisdiction of the courts of Malaysia.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">8. Contact</h3>
            <p>
              For terms-related queries, contact us at{" "}
              <a href="mailto:support@aiportals.my" className="text-primary hover:underline">support@aiportals.my</a>
              {" "}or via WhatsApp at{" "}
              <a href="https://wa.me/60173678484" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">+60 17-367 8484</a>.
            </p>
          </div>
        </div>
      </section>

      <div className="border-t border-border/50" />

      <section id="privacy" className="scroll-mt-8">
        <h2 className="font-serif text-3xl font-bold mb-6 text-foreground">Privacy Policy</h2>
        <div className="space-y-5 text-muted-foreground leading-relaxed text-sm">
          <p>
            <strong className="text-foreground">Last updated: June 2025.</strong> This Privacy Policy explains how AI Portals, operated by Shahrul Mizan Ismail, collects, uses, and protects your personal data in accordance with the Personal Data Protection Act 2010 (PDPA) of Malaysia.
          </p>

          <div>
            <h3 className="font-semibold text-foreground mb-2">1. Information We Collect</h3>
            <p>
              When you subscribe, we collect your name, email address, contact number, and payment confirmation details. When you use the Platform, we may collect usage logs (e.g. queries made) to improve the service. We do not collect sensitive personal data beyond what is necessary for subscription activation and support.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">2. How We Use Your Information</h3>
            <p>
              We use your personal data to: (a) activate and manage your subscription; (b) communicate service updates, including new portal launches you have pre-ordered; (c) provide customer support; and (d) comply with legal obligations. We do not sell your personal data to third parties.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">3. Data Sharing</h3>
            <p>
              We may share your data with technology service providers who support the operation of the Platform (e.g. hosting, email delivery), strictly for operational purposes and bound by confidentiality obligations. We do not share your data with advertisers or unrelated third parties.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">4. Data Retention</h3>
            <p>
              We retain your personal data for the duration of your subscription and for up to three (3) years thereafter for record-keeping and legal compliance purposes. You may request deletion of your personal data after your subscription has expired by contacting us.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">5. Your Rights</h3>
            <p>
              Under the PDPA, you have the right to access and correct your personal data held by us. To exercise these rights, or to withdraw consent for data processing, contact us at{" "}
              <a href="mailto:support@aiportals.my" className="text-primary hover:underline">support@aiportals.my</a>.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">6. Cookies and Analytics</h3>
            <p>
              The Platform may use cookies or similar technologies to maintain your session and improve user experience. We may use anonymised analytics to understand usage patterns. We do not use tracking cookies for advertising purposes.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">7. Security</h3>
            <p>
              We take reasonable technical and organisational measures to protect your personal data against unauthorised access, disclosure, or loss. However, no internet-based transmission is completely secure, and we cannot guarantee absolute security.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">8. Contact</h3>
            <p>
              For privacy-related queries or data access requests, contact us at{" "}
              <a href="mailto:support@aiportals.my" className="text-primary hover:underline">support@aiportals.my</a>
              {" "}or via WhatsApp at{" "}
              <a href="https://wa.me/60173678484" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">+60 17-367 8484</a>.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
